In [1]:
.libPaths("/home/mattia/miniconda3/envs/Signac/lib/R/library")

In [53]:
library(tidyverse)
library(IRanges)
library(dplyr)
library(plyranges)
library(ChIPpeakAnno)
library(tibble)
library(readr)
library(biomaRt)
library(plyranges)
setwd("/proj/tmp/tmp_MZ/.snakemake/analysis")

ERROR: Error in setwd("/proj/tmp/tmp_MZ/.snakemake/analysis"): cannot change working directory

In [3]:
#Obtain TSS coordinates for all human genome:

TSS <- TSS.human.GRCh38 %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  dplyr::rename(Geneid=1,chr=2) 


# Define the prefix you want to add
prefix <- "chr"

# Add the prefix to the chromosome names using subseqnames
TSS$chr <- paste0(prefix, TSS$chr)

# Print the modified GRanges object
TSS


Geneid <- TSS$Geneid

ensembl <- useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")

listAttributes(ensembl)


TSS_symbol <- getBM(attributes = c("external_gene_name","ensembl_gene_id"),filters = "ensembl_gene_id",values = Geneid,mart = ensembl) %>% 
  dplyr::rename(SYMBOL=1,
                Geneid=2)

TSS <- inner_join(TSS,TSS_symbol) %>% 
  dplyr::rename(chr=2,start=3,end=4) %>% 
  makeGRangesFromDataFrame(keep.extra.columns = T) %>% 
  as.data.frame()%>% 
  dplyr::rename(chr=1,start=2,end=3, strand=5)%>% 
  write_delim("TSS_hg38_list",
              delim="\t",col_names = T)

TSS

      Geneid          chr  start    end      width  strand
1     ENSG00000223972 chr1  11869    14409     2541 +
2     ENSG00000227232 chr1  14404    29570    15167 -
3     ENSG00000278267 chr1  17369    17436       68 -
4     ENSG00000243485 chr1  29554    31109     1556 +
5     ENSG00000274890 chr1  30366    30503      138 +
6     ENSG00000237613 chr1  34554    36081     1528 -
7     ENSG00000268020 chr1  52473    53312      840 +
8     ENSG00000240361 chr1  62948    63887      940 +
9     ENSG00000186092 chr1  69091    70008      918 +
10    ENSG00000238009 chr1  89295   133723    44429 -
11    ENSG00000239945 chr1  89551    91105     1555 -
12    ENSG00000233750 chr1 131025   134836     3812 +
13    ENSG00000268903 chr1 135141   135895      755 -
14    ENSG00000269981 chr1 137682   137965      284 -
15    ENSG00000239906 chr1 139790   140339      550 -
16    ENSG00000241860 chr1 141474   173862    32389 -
17    ENSG00000222623 chr1 157784   157887      104 -
18    ENSG00000241599 chr1 160446   161525     1080 +
19    ENSG00000279928 chr1 182393   184158     1766 +
20    ENSG00000279457 chr1 184923   200322    15400 -
21    ENSG00000273874 chr1 187891   187958       68 -
22    ENSG00000275135 chr1 200880   201017      138 +
23    ENSG00000228463 chr1 257864   297502    39639 -
24    ENSG00000241670 chr1 258568   259024      457 -
25    ENSG00000236679 chr1 347982   348366      385 -
26    ENSG00000236743 chr1 357383   359681     2299 -
27    ENSG00000236601 chr1 358857   365704     6848 +
28    ENSG00000237094 chr1 365389   501617   136229 -
29    ENSG00000269732 chr1 439870   440232      363 +
30    ENSG00000278566 chr1 450740   451678      939 -
⋮     ⋮               ⋮    ⋮        ⋮        ⋮      ⋮
64756 ENSG00000232695 chrY 25860943 25861268   326  +
64757 ENSG00000235511 chrY 25871931 25898653 26723  -
64758 ENSG00000232914 chrY 25904518 25907250  2733  +
64759 ENSG00000223655 chrY 25918323 25918895   573  -
64760 ENSG00000230854 chrY 25923388 25929826  6439  +
64761 ENSG00000252625 chrY 25928979 25929142   164  +
64762 ENSG00000227635 chrY 25933833 25935881  2049  -
64763 ENSG00000237546 chrY 25943268 25954152 10885  +
64764 ENSG00000172283 chrY 25975549 25988069 12521  +
64765 ENSG00000227867 chrY 25991241 25991572   332  -
64766 ENSG00000231716 chrY 25994684 25995697  1014  -
64767 ENSG00000234744 chrY 26002254 26008856  6603  +
64768 ENSG00000233156 chrY 26011435 26012237   803  +
64769 ENSG00000234888 chrY 26055779 26088493 32715  -
64770 ENSG00000215507 chrY 26123674 26133308  9635  +
64771 ENSG00000235014 chrY 26198331 26208148  9818  -
64772 ENSG00000225876 chrY 26244351 26244573   223  -
64773 ENSG00000251796 chrY 26247384 26247521   138  +
64774 ENSG00000229238 chrY 26277923 26354418 76496  -
64775 ENSG00000252948 chrY 26360989 26361092   104  +
64776 ENSG00000233843 chrY 26400611 26401230   620  +
64777 ENSG00000188399 chrY 26409815 26420535 10721  +
64778 ENSG00000275510 chrY 26411059 26411158   100  -
64779 ENSG00000277146 chrY 26453982 26454092   111  +
64780 ENSG00000215506 chrY 26508213 26579690 71478  +
64781 ENSG00000224240 chrY 26549425 26549743   319  +
64782 ENSG00000227629 chrY 26586642 26591601  4960  -
64783 ENSG00000237917 chrY 26594851 26634652 39802  -
64784 ENSG00000231514 chrY 26626520 26627159   640  -
64785 ENSG00000235857 chrY 56855244 56855488   245  +
      description
1     DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 [Source:HGNC Symbol;Acc:HGNC:37102]
2     WAS protein family homolog 7 pseudogene [Source:HGNC Symbol;Acc:HGNC:38034]
3     microRNA 6859-1 [Source:HGNC Symbol;Acc:HGNC:50039]
4     microRNA 1302-11 [Source:HGNC Symbol;Acc:HGNC:38246]
5     microRNA 1302-9 [Source:HGNC Symbol;Acc:HGNC:38218]
6     family with sequence similarity 138, member A [Source:HGNC Symbol;Acc:HGNC:32334]
7     olfactory receptor, family 4, subfamily G, member 4 pseudogene [Source:HGNC Symbol;Acc:HGNC:14822]
8     olfactory receptor, family 4, subfamily G, member 11 pseudogene [Source:HGNC Symbol;Acc:HGNC:31276]
9     olfactory receptor, family 4, subfamily F, member 5 [Source:HGNC Symbol;Acc:HGNC:14825]
10
11
12    capicua transcriptional repressor pseudogene 27 [Source:HGNC Symbol;Acc:HGNC:48835]
13
14
15
16
17    RNA, U6 small nuclear 1100, pseudogene [Source:HGNC Symbol;Acc:HGNC:48063]
18
19
20    cDNA FLJ51139 {ECO:0000313|EMBL:BAG63476.1}  [Source:UniProtKB/TrEMBL;Acc:B4DXR4]
21    microRNA 6859-2 [Source:HGNC Symbol;Acc:HGNC:49954]
22
23
24
25
26
27
28
29    WW domain binding protein 1-like pseudogene 7 [Source:HGNC Symbol;Acc:HGNC:43955]
30    olfactory receptor, family 4, subfamily F, member 29 [Source:HGNC Symbol;Acc:HGNC:31275]
⋮     ⋮
64756 transcription elongation factor B (SIII), polypeptide 1 pseudogene 17 [Source:HGNC Symbol;Acc:HGNC:38153]
64757 OFD1 pseudogene 18, Y-linked [Source:HGNC Symbol;Acc:HGNC:2589]
64758 trafficking protein particle complex 2 pseudogene 4 [Source:HGNC Symbol;Acc:HGNC:10713]
64759 RAB9A, member RAS oncogene family pseudogene 3 [Source:HGNC Symbol;Acc:HGNC:38107]
64760 ubiquitin specific peptidase 9, Y-linked pseudogene 20 [Source:HGNC Symbol;Acc:HGNC:38767]
64761 RNA, U1 small nuclear 40, pseudogene [Source:HGNC Symbol;Acc:HGNC:48382]
64762 ubiquitin specific peptidase 9, Y-linked pseudogene 21 [Source:HGNC Symbol;Acc:HGNC:38757]
64763 XK, Kell blood group complex subunit-related, Y-linked pseudogene 6 [Source:HGNC Symbol;Acc:HGNC:23913]
64764 PTPN13-like, Y-linked pseudogene 4 [Source:HGNC Symbol;Acc:HGNC:34021]
64765 transcription elongation factor B (SIII), polypeptide 1 pseudogene 11 [Source:HGNC Symbol;Acc:HGNC:38147]
64766 chromodomain protein, Y-linked 23 pseudogene [Source:HGNC Symbol;Acc:HGNC:23867]
64767 ubiquitin specific peptidase 9, Y-linked pseudogene 26 [Source:HGNC Symbol;Acc:HGNC:38762]
64768 heat shock transcription factor, Y linked 8, pseudogene [Source:HGNC Symbol;Acc:HGNC:38792]
64769 OFD1 pseudogene 15, Y-linked [Source:HGNC Symbol;Acc:HGNC:23887]
64770 RNA binding motif protein, Y-linked, family 2, member D pseudogene [Source:HGNC Symbol;Acc:HGNC:23259]
64771 arginine-glutamic acid dipeptide (RE) repeats pseudogene 2, Y-linked [Source:HGNC Symbol;Acc:HGNC:38796]
64772
64773 Small nucleolar RNA SNORA70 [Source:RFAM;Acc:RF00156]
64774 protein phosphatase 1, regulatory subunit 12B pseudogene, Y-linked 1 [Source:HGNC Symbol;Acc:HGNC:18498]
64775 RNA, U6 small nuclear 1314, pseudogene [Source:HGNC Symbol;Acc:HGNC:48277]
64776 cytochrome c, somatic pseudogene 48 [Source:HGNC Symbol;Acc:HGNC:23942]
64777 ankyrin repeat domain 36 pseudogene 1 [Source:HGNC Symbol;Acc:HGNC:37759]
64778
64779
64780 transmembrane phosphoinositide 3-phosphatase and tensin homolog 2 pseudogene 4 [Source:HGNC Symbol;Acc:HGNC:38077]
64781 cytochrome c, somatic pseudogene 49 [Source:HGNC Symbol;Acc:HGNC:23943]
64782 solute carrier family 25 (mitochondrial carrier; ornithine transporter) member 15 pseudogene 1 [Source:HGNC Symbol;Acc:HGNC:18497]
64783 poly (ADP-ribose) polymerase family, member 4 pseudogene 1 [Source:HGNC Symbol;Acc:HGNC:18500]
64784 family with sequence similarity 58, member C, pseudogene [Source:HGNC Symbol;Acc:HGNC:38436]
64785 C-terminal binding protein 2 pseudogene 1 [Source:HGNC Symbol;Acc:HGNC:23940]

     name
1    ensembl_gene_id
2    ensembl_gene_id_version
3    ensembl_transcript_id
4    ensembl_transcript_id_version
5    ensembl_peptide_id
6    ensembl_peptide_id_version
7    ensembl_exon_id
8    description
9    chromosome_name
10   start_position
11   end_position
12   strand
13   band
14   transcript_start
15   transcript_end
16   transcription_start_site
17   transcript_length
18   transcript_tsl
19   transcript_gencode_basic
20   transcript_appris
21   transcript_is_canonical
22   transcript_mane_select
23   transcript_mane_plus_clinical
24   external_gene_name
25   external_gene_source
26   external_transcript_name
27   external_transcript_source_name
28   transcript_count
29   percentage_gene_gc_content
30   gene_biotype
⋮    ⋮
3140 5_utr_end
3141 3_utr_start
3142 3_utr_end
3143 ensembl_transcript_id
3144 ensembl_transcript_id_version
3145 ensembl_peptide_id
3146 ensembl_peptide_id_version
3147 transcript_biotype
3148 transcript_version
3149 peptide_version
3150 strand
3151 transcript_start
3152 transcript_end
3153 transcription_start_site
3154 transcript_length
3155 cds_length
3156 cds_start
3157 cds_end
3158 ensembl_exon_id
3159 exon_chrom_start
3160 exon_chrom_end
3161 strand
3162 rank
3163 phase
3164 end_phase
3165 cdna_coding_start
3166 cdna_coding_end
3167 genomic_coding_start
3168 genomic_coding_end
3169 is_constitutive
     description                                  page
1    Gene stable ID                               feature_page
2    Gene stable ID version                       feature_page
3    Transcript stable ID                         feature_page
4    Transcript stable ID version                 feature_page
5    Protein stable ID                            feature_page
6    Protein stable ID version                    feature_page
7    Exon stable ID                               feature_page
8    Gene description                             feature_page
9    Chromosome/scaffold name                     feature_page
10   Gene start (bp)                              feature_page
11   Gene end (bp)                                feature_page
12   Strand                                       feature_page
13   Karyotype band                               feature_page
14   Transcript start (bp)                        feature_page
15   Transcript end (bp)                          feature_page
16   Transcription start site (TSS)               feature_page
17   Transcript length (including UTRs and CDS)   feature_page
18   Transcript support level (TSL)               feature_page
19   GENCODE basic annotation                     feature_page
20   APPRIS annotation                            feature_page
21   Ensembl Canonical                            feature_page
22   RefSeq match transcript (MANE Select)        feature_page
23   RefSeq match transcript (MANE Plus Clinical) feature_page
24   Gene name                                    feature_page
25   Source of gene name                          feature_page
26   Transcript name                              feature_page
27   Source of transcript name                    feature_page
28   Transcript count                             feature_page
29   Gene % GC content                            feature_page
30   Gene type                                    feature_page
⋮    ⋮                                            ⋮
3140 5' UTR end                                   sequences
3141 3' UTR start                                 sequences
3142 3' UTR end                                   sequences
3143 Transcript stable ID                         sequences
3144 Transcript stable ID version                 sequences
3145 Protein stable ID                            sequences
3146 Protein stable ID version                    sequences
3147 Transcript type                              sequences
3148 Version (transcript)                         sequences
3149 Version (protein)                            sequences
3150 Strand                                       sequences
3151 Transcript start (bp)                        sequences
3152 Transcript end (bp)                          sequences
3153 Transcription start site (TSS)               sequences
3154 Transcript length (including UTRs and CDS)   sequences
3155 CDS Length                                   sequences
3156 CDS start                                    sequences
3157 CDS end                                      sequences
3158 Exon stable ID                               sequences
3159 Exon region start (bp)                       sequences
3160 Exon region end (bp)                         sequences
3161 Strand                                       sequences
3162 Exon rank in transcript                      sequences
3163 Start phase                                  sequences
3164 End phase                                    sequences
3165 cDNA coding start                            sequences
3166 cDNA coding end                              sequences
3167 Genomic coding start                         sequences
3168 Genomic coding end                           sequences
3169 Constitutive exon                            sequences

Joining with `by = join_by(Geneid)`

      chr  start    end      width  strand Geneid
1     chr1  11869    14409     2541 +      ENSG00000223972
2     chr1  14404    29570    15167 -      ENSG00000227232
3     chr1  17369    17436       68 -      ENSG00000278267
4     chr1  29554    31109     1556 +      ENSG00000243485
5     chr1  34554    36081     1528 -      ENSG00000237613
6     chr1  52473    53312      840 +      ENSG00000268020
7     chr1  62948    63887      940 +      ENSG00000240361
8     chr1  69091    70008      918 +      ENSG00000186092
9     chr1  89295   133723    44429 -      ENSG00000238009
10    chr1  89551    91105     1555 -      ENSG00000239945
11    chr1 131025   134836     3812 +      ENSG00000233750
12    chr1 135141   135895      755 -      ENSG00000268903
13    chr1 137682   137965      284 -      ENSG00000269981
14    chr1 139790   140339      550 -      ENSG00000239906
15    chr1 141474   173862    32389 -      ENSG00000241860
16    chr1 157784   157887      104 -      ENSG00000222623
17    chr1 160446   161525     1080 +      ENSG00000241599
18    chr1 182393   184158     1766 +      ENSG00000279928
19    chr1 184923   200322    15400 -      ENSG00000279457
20    chr1 187891   187958       68 -      ENSG00000273874
21    chr1 257864   297502    39639 -      ENSG00000228463
22    chr1 347982   348366      385 -      ENSG00000236679
23    chr1 358857   365704     6848 +      ENSG00000236601
24    chr1 365389   501617   136229 -      ENSG00000237094
25    chr1 439870   440232      363 +      ENSG00000269732
26    chr1 487101   489906     2806 +      ENSG00000233653
27    chr1 491225   493241     2017 -      ENSG00000250575
28    chr1 516376   516479      104 -      ENSG00000278757
29    chr1 587629   594768     7140 +      ENSG00000235146
30    chr1 601436   724707   123272 -      ENSG00000230021
⋮     ⋮    ⋮        ⋮        ⋮      ⋮      ⋮
59758 chrY 25813013 25814566  1554  +      ENSG00000229343
59759 chrY 25860943 25861268   326  +      ENSG00000232695
59760 chrY 25871931 25898653 26723  -      ENSG00000235511
59761 chrY 25904518 25907250  2733  +      ENSG00000232914
59762 chrY 25918323 25918895   573  -      ENSG00000223655
59763 chrY 25923388 25929826  6439  +      ENSG00000230854
59764 chrY 25928979 25929142   164  +      ENSG00000252625
59765 chrY 25933833 25935881  2049  -      ENSG00000227635
59766 chrY 25943268 25954152 10885  +      ENSG00000237546
59767 chrY 25975549 25988069 12521  +      ENSG00000172283
59768 chrY 25991241 25991572   332  -      ENSG00000227867
59769 chrY 25994684 25995697  1014  -      ENSG00000231716
59770 chrY 26002254 26008856  6603  +      ENSG00000234744
59771 chrY 26011435 26012237   803  +      ENSG00000233156
59772 chrY 26055779 26088493 32715  -      ENSG00000234888
59773 chrY 26123674 26133308  9635  +      ENSG00000215507
59774 chrY 26198331 26208148  9818  -      ENSG00000235014
59775 chrY 26244351 26244573   223  -      ENSG00000225876
59776 chrY 26247384 26247521   138  +      ENSG00000251796
59777 chrY 26277923 26354418 76496  -      ENSG00000229238
59778 chrY 26360989 26361092   104  +      ENSG00000252948
59779 chrY 26400611 26401230   620  +      ENSG00000233843
59780 chrY 26409815 26420535 10721  +      ENSG00000188399
59781 chrY 26453982 26454092   111  +      ENSG00000277146
59782 chrY 26508213 26579690 71478  +      ENSG00000215506
59783 chrY 26549425 26549743   319  +      ENSG00000224240
59784 chrY 26586642 26591601  4960  -      ENSG00000227629
59785 chrY 26594851 26634652 39802  -      ENSG00000237917
59786 chrY 26626520 26627159   640  -      ENSG00000231514
59787 chrY 56855244 56855488   245  +      ENSG00000235857
      description
1     DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 [Source:HGNC Symbol;Acc:HGNC:37102]
2     WAS protein family homolog 7 pseudogene [Source:HGNC Symbol;Acc:HGNC:38034]
3     microRNA 6859-1 [Source:HGNC Symbol;Acc:HGNC:50039]
4     microRNA 1302-11 [Source:HGNC Symbol;Acc:HGNC:38246]
5     family with sequence similarity 138, member A [Source:HGNC Symbol;Acc:HGNC:32334]
6     olfactory receptor, family 4, subfamily G, member 4 pseudogene [Source:HGNC Symbol;Acc:HGNC:14822]
7     olfactory receptor, family 4, subfamily G, member 11 pseudogene [Source:HGNC Symbol;Acc:HGNC:31276]
8     olfactory receptor, family 4, subfamily F, member 5 [Source:HGNC Symbol;Acc:HGNC:14825]
9
10
11    capicua transcriptional repressor pseudogene 27 [Source:HGNC Symbol;Acc:HGNC:48835]
12
13
14
15
16    RNA, U6 small nuclear 1100, pseudogene [Source:HGNC Symbol;Acc:HGNC:48063]
17
18
19    cDNA FLJ51139 {ECO:0000313|EMBL:BAG63476.1}  [Source:UniProtKB/TrEMBL;Acc:B4DXR4]
20    microRNA 6859-2 [Source:HGNC Symbol;Acc:HGNC:49954]
21
22
23
24
25    WW domain binding protein 1-like pseudogene 7 [Source:HGNC Symbol;Acc:HGNC:43955]
26    capicua transcriptional repressor pseudogene 7 [Source:HGNC Symbol;Acc:HGNC:37756]
27
28    U6 spliceosomal RNA [Source:RFAM;Acc:RF00026]
29
30
⋮     ⋮
59758 chromodomain protein, Y-linked 22 pseudogene [Source:HGNC Symbol;Acc:HGNC:23866]
59759 transcription elongation factor B (SIII), polypeptide 1 pseudogene 17 [Source:HGNC Symbol;Acc:HGNC:38153]
59760 OFD1 pseudogene 18, Y-linked [Source:HGNC Symbol;Acc:HGNC:2589]
59761 trafficking protein particle complex 2 pseudogene 4 [Source:HGNC Symbol;Acc:HGNC:10713]
59762 RAB9A, member RAS oncogene family pseudogene 3 [Source:HGNC Symbol;Acc:HGNC:38107]
59763 ubiquitin specific peptidase 9, Y-linked pseudogene 20 [Source:HGNC Symbol;Acc:HGNC:38767]
59764 RNA, U1 small nuclear 40, pseudogene [Source:HGNC Symbol;Acc:HGNC:48382]
59765 ubiquitin specific peptidase 9, Y-linked pseudogene 21 [Source:HGNC Symbol;Acc:HGNC:38757]
59766 XK, Kell blood group complex subunit-related, Y-linked pseudogene 6 [Source:HGNC Symbol;Acc:HGNC:23913]
59767 PTPN13-like, Y-linked pseudogene 4 [Source:HGNC Symbol;Acc:HGNC:34021]
59768 transcription elongation factor B (SIII), polypeptide 1 pseudogene 11 [Source:HGNC Symbol;Acc:HGNC:38147]
59769 chromodomain protein, Y-linked 23 pseudogene [Source:HGNC Symbol;Acc:HGNC:23867]
59770 ubiquitin specific peptidase 9, Y-linked pseudogene 26 [Source:HGNC Symbol;Acc:HGNC:38762]
59771 heat shock transcription factor, Y linked 8, pseudogene [Source:HGNC Symbol;Acc:HGNC:38792]
59772 OFD1 pseudogene 15, Y-linked [Source:HGNC Symbol;Acc:HGNC:23887]
59773 RNA binding motif protein, Y-linked, family 2, member D pseudogene [Source:HGNC Symbol;Acc:HGNC:23259]
59774 arginine-glutamic acid dipeptide (RE) repeats pseudogene 2, Y-linked [Source:HGNC Symbol;Acc:HGNC:38796]
59775
59776 Small nucleolar RNA SNORA70 [Source:RFAM;Acc:RF00156]
59777 protein phosphatase 1, regulatory subunit 12B pseudogene, Y-linked 1 [Source:HGNC Symbol;Acc:HGNC:18498]
59778 RNA, U6 small nuclear 1314, pseudogene [Source:HGNC Symbol;Acc:HGNC:48277]
59779 cytochrome c, somatic pseudogene 48 [Source:HGNC Symbol;Acc:HGNC:23942]
59780 ankyrin repeat domain 36 pseudogene 1 [Source:HGNC Symbol;Acc:HGNC:37759]
59781
59782 transmembrane phosphoinositide 3-phosphatase and tensin homolog 2 pseudogene 4 [Source:HGNC Symbol;Acc:HGNC:38077]
59783 cytochrome c, somatic pseudogene 49 [Source:HGNC Symbol;Acc:HGNC:23943]
59784 solute carrier family 25 (mitochondrial carrier; ornithine transporter) member 15 pseudogene 1 [Source:HGNC Symbol;Acc:HGNC:18497]
59785 poly (ADP-ribose) polymerase family, member 4 pseudogene 1 [Source:HGNC Symbol;Acc:HGNC:18500]
59786 family with sequence similarity 58, member C, pseudogene [Source:HGNC Symbol;Acc:HGNC:38436]
59787 C-terminal binding protein 2 pseudogene 1 [Source:HGNC Symbol;Acc:HGNC:23940]
      SYMBOL
1     DDX11L1
2     WASH7P
3     MIR6859-1
4     MIR1302-2HG
5     FAM138A
6     OR4G4P
7     OR4G11P
8     OR4F5
9
10
11    CICP27
12
13
14
15
16    RNU6-1100P
17
18    DDX11L17
19    WASH9P
20    MIR6859-2
21
22    RPL23AP24
23
24
25    WBP1LP7
26    CICP7
27
28    U6
29
30
⋮     ⋮
59758 CDY22P
59759 ELOCP17
59760 OFD1P18Y
59761 TRAPPC2P4
59762 RAB9AP3
59763 USP9YP20
59764 RNU1-40P
59765 USP9YP21
59766 XKRYP6
59767 PRYP4
59768 ELOCP11
59769 CDY23P
59770 USP9YP26
59771 HSFY8P
59772 OFD1P15Y
59773 RBMY2DP
59774 REREP2Y
59775
59776 SNORA70
59777 PPP1R12BP1
59778 RNU6-1314P
59779 CYCSP48
59780 ANKRD36P1
59781
59782 TPTE2P4
59783 CYCSP49
59784 SLC25A15P1
59785 PARP4P1
59786 CCNQP2
59787 CTBP2P1

Here we calculate counts in Hg38 for H3K27ac samples Paried end

In [24]:
#Calculate correlation between TSS using Deseq2

library (DESeq2)
library(Rsubread)
#Bam files list where to perform Counts calculation

bamsToCount <- dir("/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac", full.names = TRUE, pattern = "*.\\.bam$")
bamsToCount
# Calculate differential accessibility using DESEQ2

consensusToCount <- read_delim("TSS_hg38_list",  #list of regions where to perform calculation
                                delim="\t",col_names = T)%>% 
                                makeGRangesFromDataFrame(keep.extra.columns = T)
                               


regionsToCount <- data.frame(GeneID = paste(seqnames(consensusToCount), 
                                            start(consensusToCount), end(consensusToCount), sep = "_"), chr = seqnames(consensusToCount), 
                             start = start(consensusToCount), end = end(consensusToCount), Strand = strand(consensusToCount)) 


fcResults_PE <- featureCounts(bamsToCount, annot.ext = regionsToCount, isPairedEnd = TRUE,
                           countMultiMappingReads = FALSE, maxFragLength = 100,
                           nthreads = 20)


myCounts_PE <- fcResults$counts

myCounts_PE

 [1] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/04061-C-100_H3K27ac_ChIP.bam"
 [2] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/04061-C-200_H3K27ac_ChIP.bam"
 [3] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/04061-P-100_H3K27ac_Cut-Tag_broad.bam"
 [4] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/04061-P-100_H3K27ac_Cut-Tag.bam"
 [5] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/04061-P-200_H3K27ac_Cut-Tag_broad.bam"
 [6] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/04061-P-200_H3K27ac_Cut-Tag.bam"
 [7] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/12097-C_H3K27ac_ChIP.bam"
 [8] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/12097-C_H3K27ac_Cut-Tag_broad.bam"
 [9] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/12097-C_H3K27ac_Cut-Tag.bam"
[10] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/12097-P_H3K27ac_ChIP.bam"
[11] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/14223-C_H3K27ac_ChIP.bam"
[12] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/14223-C_H3K27ac_Cut-Tag_broad.bam"
[13] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/14223-C_H3K27ac_Cut-Tag.bam"
[14] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/14223-P_H3K27ac_ChIP.bam"
[15] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/14223-P_H3K27ac_Cut-Tag_broad.bam"
[16] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/14223-P_H3K27ac_Cut-Tag.bam"
[17] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/16057-P-100_H3K27ac_ChIP.bam"
[18] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/16057-P-100_H3K27ac_Cut-Tag_broad.bam"
[19] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/16057-P-100_H3K27ac_Cut-Tag.bam"
[20] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/16057-P-200_H3K27ac_ChIP.bam"
[21] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/16057-P-200_H3K27ac_Cut-Tag_broad.bam"
[22] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/16057-P-200_H3K27ac_Cut-Tag.bam"
[23] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/16170-C_H3K27ac_ChIP.bam"
[24] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/16170-P_H3K27ac_ChIP.bam"
[25] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/17170-P_H3K27ac_Cut-Tag_broad.bam"
[26] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/17170-P_H3K27ac_Cut-Tag.bam"
[27] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/19019-C_H3K27ac_ChIP.bam"
[28] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/19019-C_H3K27ac_Cut-Tag_broad.bam"
[29] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/19019-C_H3K27ac_Cut-Tag.bam"
[30] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/19019-P_H3K27ac_ChIP.bam"
[31] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/19019-P_H3K27ac_Cut-Tag_broad.bam"
[32] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/19019-P_H3K27ac_Cut-Tag.bam"
[33] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/CD19-GSE172116-1_H3K27ac_ChIP.bam"
[34] "/date/gcb/gcb_MZ/Round1/dedup/picard/H3K27ac/CD19-GSE172116-2_H3K27ac_ChIP.bam"

Rows: 59787 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (5): chr, strand, Geneid, description, SYMBOL
dbl (3): start, end, width

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 2.14.2

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 34 BAM files                                     ||
||                                                                            ||
||                           04061-C-100_H3K27ac_ChIP.bam                     ||
||                           04061-C-200_H3K27ac_ChIP.bam                     ||
||                           04061-P-100_H3K27ac_Cut-Tag_broad.bam            ||
||                           04061-P-100_H3K27ac_Cut-Tag.bam                  ||
||                           04061-P-200_H3K27ac_Cut-Tag_broad.bam            ||
||                           04061-P-200_H3K27ac_Cut-Tag.bam                  ||
||                           12097-C_H3K27ac_ChIP.bam                         ||
||                           12097-C_H3K27ac_Cut-Tag_broad.bam                ||
||                           12097-C_H3K27ac_Cut-Tag.bam                      ||
||                           12097-P_H3K27ac_ChIP.bam                         ||
||                           14223-C_H3K27ac_ChIP.bam                         ||
||                           14223-C_H3K27ac_Cut-Tag_broad.bam                ||
||                           14223-C_H3K27ac_Cut-Tag.bam                      ||
||                           14223-P_H3K27ac_ChIP.bam                         ||
||                           14223-P_H3K27ac_Cut-Tag_broad.bam                ||
||                           14223-P_H3K27ac_Cut-Tag.bam                      ||
||                           16057-P-100_H3K27ac_ChIP.bam                     ||
||                           16057-P-100_H3K27ac_Cut-Tag_broad.bam            ||
||                           16057-P-100_H3K27ac_Cut-Tag.bam                  ||
||                           16057-P-200_H3K27ac_ChIP.bam                     ||
||                           16057-P-200_H3K27ac_Cut-Tag_broad.bam            ||
||                           16057-P-200_H3K27ac_Cut-Tag.bam                  ||
||                           16170-C_H3K27ac_ChIP.bam                         ||
||                           16170-P_H3K27ac_ChIP.bam                         ||
||                           17170-P_H3K27ac_Cut-Tag_broad.bam                ||
||                           17170-P_H3K27ac_Cut-Tag.bam                      ||
||                           19019-C_H3K27ac_ChIP.bam                         ||
||                           19019-C_H3K27ac_Cut-Tag_broad.bam                ||
||                           19019-C_H3K27ac_Cut-Tag.bam                      ||
||                           19019-P_H3K27ac_ChIP.bam                         ||
||                           19019-P_H3K27ac_Cut-Tag_broad.bam                ||
||                           19019-P_H3K27ac_Cut-Tag.bam                      ||
||                           CD19-GSE172116-1_H3K27ac_ChIP.bam                ||
||                           CD19-GSE172116-2_H3K27ac_ChIP.bam                ||
||                                                                            ||
||              Paired-end : yes                                              ||
||        Count read pairs : yes                                              ||
||              Annotation : R data.frame                                     ||
||      Dir for temp files : .                                                ||
||                 Threads : 20                                               ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid2658151 ...       ||
||    Features : 59787                                                        ||
||    Meta-features : 59786                                                   ||
||    Chromosomes/contigs : 250                                               ||
||                                                                            ||
|| Process BAM file 04061-C-100_H3K27ac_ChIP.bam...                           ||
||                                                                            ||
|| WARNING: more than 10 'M' segments were found in CIGAR string.             ||
|| The exceeding sections are not useed. Please consider to increase maxMOp.  ||
||                                                                            ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 12658872                                             ||
||    Successfully assigned alignments : 134206 (1.1%)                        ||
||    Running time : 0.04 minutes                                             ||
||                                                                            ||
|| Process BAM file 04061-C-200_H3K27ac_ChIP.bam...                           ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 8559543                                              ||
||    Successfully assigned alignments : 275355 (3.2%)                        ||
||    Running time : 0.03 minutes                                             ||
||                                                                            ||
|| Process BAM file 04061-P-100_H3K27ac_Cut-Tag_broad.bam...                  ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 1703319                                              ||
||    Successfully assigned alignments : 563386 (33.1%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 04061-P-100_H3K27ac_Cut-Tag.bam...                        ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 1703319                                              ||
||    Successfully assigned alignments : 563386 (33.1%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 04061-P-200_H3K27ac_Cut-Tag_broad.bam...                  ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 6568449                                              ||
||    Successfully assigned alignments : 1746746 (26.6%)                      ||
||    Running time : 0.03 minutes                                             ||
||                                                                            ||
|| Process BAM file 04061-P-200_H3K27ac_Cut-Tag.bam...                        ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 6568449                                              ||
||    Successfully assigned alignments : 1746746 (26.6%)                      ||
||    Running time : 0.03 minutes                                             ||
||                                                                            ||
|| Process BAM file 12097-C_H3K27ac_ChIP.bam...                               ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 4918294                                              ||
||    Successfully assigned alignments : 617584 (12.6%)                       ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 12097-C_H3K27ac_Cut-Tag_broad.bam...                      ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 2090777                                              ||
||    Successfully assigned alignments : 737146 (35.3%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 12097-C_H3K27ac_Cut-Tag.bam...                            ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 2090777                                              ||
||    Successfully assigned alignments : 737146 (35.3%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 12097-P_H3K27ac_ChIP.bam...                               ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 6496476                                              ||
||    Successfully assigned alignments : 1012116 (15.6%)                      ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 14223-C_H3K27ac_ChIP.bam...                               ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 5533532                                              ||
||    Successfully assigned alignments : 345923 (6.3%)                        ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 14223-C_H3K27ac_Cut-Tag_broad.bam...                      ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 1097893                                              ||
||    Successfully assigned alignments : 228270 (20.8%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 14223-C_H3K27ac_Cut-Tag.bam...                            ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 1097893                                              ||
||    Successfully assigned alignments : 228270 (20.8%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 14223-P_H3K27ac_ChIP.bam...                               ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 9565366                                              ||
||    Successfully assigned alignments : 2013876 (21.1%)                      ||
||    Running time : 0.03 minutes                                             ||
||                                                                            ||
|| Process BAM file 14223-P_H3K27ac_Cut-Tag_broad.bam...                      ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 1286039                                              ||
||    Successfully assigned alignments : 207441 (16.1%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 14223-P_H3K27ac_Cut-Tag.bam...                            ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 1286039                                              ||
||    Successfully assigned alignments : 207441 (16.1%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 16057-P-100_H3K27ac_ChIP.bam...                           ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 10937758                                             ||
||    Successfully assigned alignments : 888395 (8.1%)                        ||
||    Running time : 0.03 minutes                                             ||
||                                                                            ||
|| Process BAM file 16057-P-100_H3K27ac_Cut-Tag_broad.bam...                  ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 3273137                                              ||
||    Successfully assigned alignments : 1400866 (42.8%)                      ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 16057-P-100_H3K27ac_Cut-Tag.bam...                        ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 3273137                                              ||
||    Successfully assigned alignments : 1400866 (42.8%)                      ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 16057-P-200_H3K27ac_ChIP.bam...                           ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 5215854                                              ||
||    Successfully assigned alignments : 805134 (15.4%)                       ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 16057-P-200_H3K27ac_Cut-Tag_broad.bam...                  ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 3609119                                              ||
||    Successfully assigned alignments : 1591918 (44.1%)                      ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 16057-P-200_H3K27ac_Cut-Tag.bam...                        ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 3609119                                              ||
||    Successfully assigned alignments : 1591918 (44.1%)                      ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 16170-C_H3K27ac_ChIP.bam...                               ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 3804288                                              ||
||    Successfully assigned alignments : 908160 (23.9%)                       ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 16170-P_H3K27ac_ChIP.bam...                               ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 5331727                                              ||
||    Successfully assigned alignments : 154556 (2.9%)                        ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file 17170-P_H3K27ac_Cut-Tag_broad.bam...                      ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 10049150                                             ||
||    Successfully assigned alignments : 4093069 (40.7%)                      ||
||    Running time : 0.04 minutes                                             ||
||                                                                            ||
|| Process BAM file 17170-P_H3K27ac_Cut-Tag.bam...                            ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 10049150                                             ||
||    Successfully assigned alignments : 4093069 (40.7%)                      ||
||    Running time : 0.04 minutes                                             ||
||                                                                            ||
|| Process BAM file 19019-C_H3K27ac_ChIP.bam...                               ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 10730950                                             ||
||    Successfully assigned alignments : 196277 (1.8%)                        ||
||    Running time : 0.03 minutes                                             ||
||                                                                            ||
|| Process BAM file 19019-C_H3K27ac_Cut-Tag_broad.bam...                      ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 132997                                               ||
||    Successfully assigned alignments : 22486 (16.9%)                        ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 19019-C_H3K27ac_Cut-Tag.bam...                            ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 132997                                               ||
||    Successfully assigned alignments : 22486 (16.9%)                        ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file 19019-P_H3K27ac_ChIP.bam...                               ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 15452910                                             ||
||    Successfully assigned alignments : 2312510 (15.0%)                      ||
||    Running time : 0.05 minutes                                             ||
||                                                                            ||

                       04061-C-100_H3K27ac_ChIP.bam
chr1_11869_14409        1
chr1_14404_29570        1
chr1_17369_17436        0
chr1_29554_31109        0
chr1_34554_36081        0
chr1_52473_53312        0
chr1_62948_63887        0
chr1_69091_70008        0
chr1_89295_133723       4
chr1_89551_91105        0
chr1_131025_134836      0
chr1_135141_135895      0
chr1_137682_137965      0
chr1_139790_140339      0
chr1_141474_173862      2
chr1_157784_157887      0
chr1_160446_161525      0
chr1_182393_184158      0
chr1_184923_200322      3
chr1_187891_187958      0
chr1_257864_297502      7
chr1_347982_348366      0
chr1_358857_365704      2
chr1_365389_501617     21
chr1_439870_440232      0
chr1_487101_489906      0
chr1_491225_493241      0
chr1_516376_516479      0
chr1_587629_594768      0
chr1_601436_724707     12
⋮                      ⋮
chrY_25813013_25814566 0
chrY_25860943_25861268 0
chrY_25871931_25898653 2
chrY_25904518_25907250 0
chrY_25918323_25918895 0
chrY_25923388_25929826 0
chrY_25928979_25929142 0
chrY_25933833_25935881 0
chrY_25943268_25954152 0
chrY_25975549_25988069 1
chrY_25991241_25991572 0
chrY_25994684_25995697 0
chrY_26002254_26008856 0
chrY_26011435_26012237 0
chrY_26055779_26088493 2
chrY_26123674_26133308 1
chrY_26198331_26208148 0
chrY_26244351_26244573 0
chrY_26247384_26247521 0
chrY_26277923_26354418 5
chrY_26360989_26361092 0
chrY_26400611_26401230 0
chrY_26409815_26420535 0
chrY_26453982_26454092 1
chrY_26508213_26579690 1
chrY_26549425_26549743 0
chrY_26586642_26591601 2
chrY_26594851_26634652 3
chrY_26626520_26627159 0
chrY_56855244_56855488 1
                       04061-C-200_H3K27ac_ChIP.bam
chr1_11869_14409        1
chr1_14404_29570        4
chr1_17369_17436        0
chr1_29554_31109        0
chr1_34554_36081        1
chr1_52473_53312        1
chr1_62948_63887        0
chr1_69091_70008        1
chr1_89295_133723      19
chr1_89551_91105        0
chr1_131025_134836      0
chr1_135141_135895      1
chr1_137682_137965      0
chr1_139790_140339      0
chr1_141474_173862     10
chr1_157784_157887      0
chr1_160446_161525      0
chr1_182393_184158      2
chr1_184923_200322      5
chr1_187891_187958      0
chr1_257864_297502     14
chr1_347982_348366      0
chr1_358857_365704      1
chr1_365389_501617     28
chr1_439870_440232      0
chr1_487101_489906      0
chr1_491225_493241      0
chr1_516376_516479      0
chr1_587629_594768      1
chr1_601436_724707     34
⋮                      ⋮
chrY_25813013_25814566 0
chrY_25860943_25861268 0
chrY_25871931_25898653 0
chrY_25904518_25907250 0
chrY_25918323_25918895 0
chrY_25923388_25929826 1
chrY_25928979_25929142 0
chrY_25933833_25935881 0
chrY_25943268_25954152 0
chrY_25975549_25988069 0
chrY_25991241_25991572 0
chrY_25994684_25995697 0
chrY_26002254_26008856 0
chrY_26011435_26012237 0
chrY_26055779_26088493 3
chrY_26123674_26133308 4
chrY_26198331_26208148 1
chrY_26244351_26244573 0
chrY_26247384_26247521 0
chrY_26277923_26354418 5
chrY_26360989_26361092 0
chrY_26400611_26401230 0
chrY_26409815_26420535 1
chrY_26453982_26454092 0
chrY_26508213_26579690 5
chrY_26549425_26549743 0
chrY_26586642_26591601 0
chrY_26594851_26634652 2
chrY_26626520_26627159 0
chrY_56855244_56855488 0
                       04061-P-100_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409         5
chr1_14404_29570         6
chr1_17369_17436         0
chr1_29554_31109         4
chr1_34554_36081         2
chr1_52473_53312         0
chr1_62948_63887         0
chr1_69091_70008         0
chr1_89295_133723       19
chr1_89551_91105         0
chr1_131025_134836       0
chr1_135141_135895       0
chr1_137682_137965       1
chr1_139790_140339       2
chr1_141474_173862      20
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       1
chr1_184923_200322      19
chr1_187891_187958       0
chr1_257864_297502      45
chr1_347982_348366       1
chr1_358857_365704       1
chr1_365389_501617     123
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       0
chr1_587629_594768       4
chr1_601436_724707     102
⋮                      ⋮
chrY_25813013_25814566  0
chrY_25860943_25861268  0
chrY_25871931_25898653  2
chrY_25904518_25907250  0
chrY_25918323_25918895  0
chrY_25923388_25929826  0
chrY_25928979_25929142  0
chrY_25933833_25935881  0
chrY_25943268_25954152  4
chrY_25975549_25988069  3
chrY_25991241_25991572  0
chrY_25994684_25995697  1
chrY_26002254_26008856  0
chrY_26011435_26012237  0
chrY_26055779_26088493  8
chrY_26123674_26133308  0
chrY_26198331_26208148  0
chrY_26244351_26244573  0
chrY_26247384_26247521  0
chrY_26277923_26354418 22
chrY_26360989_26361092  0
chrY_26400611_26401230  0
chrY_26409815_26420535  0
chrY_26453982_26454092  0
chrY_26508213_26579690 14
chrY_26549425_26549743  0
chrY_26586642_26591601  0
chrY_26594851_26634652  9
chrY_26626520_26627159  0
chrY_56855244_56855488  0
                       04061-P-100_H3K27ac_Cut-Tag.bam
chr1_11869_14409         5
chr1_14404_29570         6
chr1_17369_17436         0
chr1_29554_31109         4
chr1_34554_36081         2
chr1_52473_53312         0
chr1_62948_63887         0
chr1_69091_70008         0
chr1_89295_133723       19
chr1_89551_91105         0
chr1_131025_134836       0
chr1_135141_135895       0
chr1_137682_137965       1
chr1_139790_140339       2
chr1_141474_173862      20
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       1
chr1_184923_200322      19
chr1_187891_187958       0
chr1_257864_297502      45
chr1_347982_348366       1
chr1_358857_365704       1
chr1_365389_501617     123
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       0
chr1_587629_594768       4
chr1_601436_724707     102
⋮                      ⋮
chrY_25813013_25814566  0
chrY_25860943_25861268  0
chrY_25871931_25898653  2
chrY_25904518_25907250  0
chrY_25918323_25918895  0
chrY_25923388_25929826  0
chrY_25928979_25929142  0
chrY_25933833_25935881  0
chrY_25943268_25954152  4
chrY_25975549_25988069  3
chrY_25991241_25991572  0
chrY_25994684_25995697  1
chrY_26002254_26008856  0
chrY_26011435_26012237  0
chrY_26055779_26088493  8
chrY_26123674_26133308  0
chrY_26198331_26208148  0
chrY_26244351_26244573  0
chrY_26247384_26247521  0
chrY_26277923_26354418 22
chrY_26360989_26361092  0
chrY_26400611_26401230  0
chrY_26409815_26420535  0
chrY_26453982_26454092  0
chrY_26508213_26579690 14
chrY_26549425_26549743  0
chrY_26586642_26591601  0
chrY_26594851_26634652  9
chrY_26626520_26627159  0
chrY_56855244_56855488  0
                       04061-P-200_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409         4
chr1_14404_29570        35
chr1_17369_17436         0
chr1_29554_31109        16
chr1_34554_36081         0
chr1_52473_53312         0
chr1_62948_63887         0
chr1_69091_70008         6
chr1_89295_133723       94
chr1_89551_91105         0
chr1_131025_134836       2
chr1_135141_135895       3
chr1_137682_137965       0
chr1_139790_140339       1
chr1_141474_173862      37
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       7
chr1_184923_200322      56
chr1_187891_187958       0
chr1_257864_297502      91
chr1_347982_348366       3
chr1_358857_365704       9
chr1_365389_501617     488
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       0
chr1_587629_594768       5
chr1_601436_724707     304
⋮                      ⋮
chrY_25813013_25814566   4
chrY_25860943_25861268   0
chrY_25871931_25898653  18
chrY_25904518_25907250   1
chrY_25918323_25918895   0
chrY_25923388_25929826   4
chrY_25928979_25929142   0
chrY_25933833_25935881   1
chrY_25943268_25954152   2
chrY_25975549_25988069   5
chrY_25991241_25991572   0
chrY_25994684_25995697   0
chrY_26002254_26008856  21
chrY_26011435_26012237   0
chrY_26055779_26088493  35
chrY_26123674_26133308   6
chrY_26198331_26208148   2
chrY_26244351_26244573   0
chrY_26247384_26247521   0
chrY_26277923_26354418 129
chrY_26360989_26361092   0
chrY_26400611_26401230   0
chrY_26409815_26420535   2
chrY_26453982_26454092   1
chrY_26508213_26579690  62
chrY_26549425_26549743   0
chrY_26586642_26591601  13
chrY_26594851_26634652  43
chrY_26626520_26627159   0
chrY_56855244_56855488   1
                       04061-P-200_H3K27ac_Cut-Tag.bam 12097-C_H3K27ac_ChIP.bam
chr1_11869_14409         4                              2
chr1_14404_29570        35                              9
chr1_17369_17436         0                              0
chr1_29554_31109        16                              0
chr1_34554_36081         0                              2
chr1_52473_53312         0                              1
chr1_62948_63887         0                              0
chr1_69091_70008         6                              0
chr1_89295_133723       94                             37
chr1_89551_91105         0                              0
chr1_131025_134836       2                              0
chr1_135141_135895       3                              0
chr1_137682_137965       0                              0
chr1_139790_140339       1                              0
chr1_141474_173862      37                             15
chr1_157784_157887       0                              0
chr1_160446_161525       0                              0
chr1_182393_184158       7                              2
chr1_184923_200322      56                              9
chr1_187891_187958       0                              0
chr1_257864_297502      91                             36
chr1_347982_348366       3                              0
chr1_358857_365704       9                              3
chr1_365389_501617     488                             62
chr1_439870_440232       0                              0
chr1_487101_489906       0                              0
chr1_491225_493241       0                              0
chr1_516376_516479       0                              0
chr1_587629_594768       5                              1
chr1_601436_724707     304                             62
⋮                      ⋮                               ⋮
chrY_25813013_25814566   4                             0
chrY_25860943_25861268   0                             0
chrY_25871931_25898653  18                             4
chrY_25904518_25907250   1                             0
chrY_25918323_25918895   0                             0
chrY_25923388_25929826   4                             0
chrY_25928979_25929142   0                             0
chrY_25933833_25935881   1                             0
chrY_25943268_25954152   2                             3
chrY_25975549_25988069   5                             1
chrY_25991241_25991572   0                             0
chrY_25994684_25995697   0                             0
chrY_26002254_26008856  21                             2
chrY_26011435_26012237   0                             0
chrY_26055779_26088493  35                             3
chrY_26123674_26133308   6                             1
chrY_26198331_26208148   2                             2
chrY_26244351_26244573   0                             0
chrY_26247384_26247521   0                             0
chrY_26277923_26354418 129                             5
chrY_26360989_26361092   0                             0
chrY_26400611_26401230   0                             0
chrY_26409815_26420535   2                             3
chrY_26453982_26454092   1                             0
chrY_26508213_26579690  62                             9
chrY_26549425_26549743   0                             0
chrY_26586642_26591601  13                             0
chrY_26594851_26634652  43                             6
chrY_26626520_26627159   0                             0
chrY_56855244_56855488   1                             0
                       12097-C_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409        2
chr1_14404_29570       23
chr1_17369_17436        0
chr1_29554_31109        1
chr1_34554_36081        2
chr1_52473_53312        2
chr1_62948_63887        0
chr1_69091_70008        0
chr1_89295_133723      19
chr1_89551_91105        0
chr1_131025_134836      1
chr1_135141_135895      1
chr1_137682_137965      0
chr1_139790_140339      1
chr1_141474_173862     16
chr1_157784_157887      0
chr1_160446_161525      0
chr1_182393_184158      0
chr1_184923_200322     24
chr1_187891_187958      0
chr1_257864_297502     44
chr1_347982_348366      0
chr1_358857_365704      4
chr1_365389_501617     65
chr1_439870_440232      0
chr1_487101_489906      0
chr1_491225_493241      0
chr1_516376_516479      0
chr1_587629_594768      3
chr1_601436_724707     76
⋮                      ⋮
chrY_25813013_25814566 0
chrY_25860943_25861268 0
chrY_25871931_25898653 0
chrY_25904518_25907250 0
chrY_25918323_25918895 0
chrY_25923388_25929826 0
chrY_25928979_25929142 0
chrY_25933833_25935881 0
chrY_25943268_25954152 0
chrY_25975549_25988069 0
chrY_25991241_25991572 0
chrY_25994684_25995697 0
chrY_26002254_26008856 0
chrY_26011435_26012237 0
chrY_26055779_26088493 2
chrY_26123674_26133308 0
chrY_26198331_26208148 0
chrY_26244351_26244573 0
chrY_26247384_26247521 0
chrY_26277923_26354418 2
chrY_26360989_26361092 0
chrY_26400611_26401230 0
chrY_26409815_26420535 0
chrY_26453982_26454092 0
chrY_26508213_26579690 4
chrY_26549425_26549743 0
chrY_26586642_26591601 1
chrY_26594851_26634652 1
chrY_26626520_26627159 0
chrY_56855244_56855488 0
                       12097-C_H3K27ac_Cut-Tag.bam 12097-P_H3K27ac_ChIP.bam ⋯
chr1_11869_14409        2                            5                      ⋯
chr1_14404_29570       23                           27                      ⋯
chr1_17369_17436        0                            0                      ⋯
chr1_29554_31109        1                            5                      ⋯
chr1_34554_36081        2                            2                      ⋯
chr1_52473_53312        2                            1                      ⋯
chr1_62948_63887        0                            0                      ⋯
chr1_69091_70008        0                            0                      ⋯
chr1_89295_133723      19                           46                      ⋯
chr1_89551_91105        0                            0                      ⋯
chr1_131025_134836      1                            3                      ⋯
chr1_135141_135895      1                            0                      ⋯
chr1_137682_137965      0                            3                      ⋯
chr1_139790_140339      1                            0                      ⋯
chr1_141474_173862     16                           23                      ⋯
chr1_157784_157887      0                            0                      ⋯
chr1_160446_161525      0                            0                      ⋯
chr1_182393_184158      0                            3                      ⋯
chr1_184923_200322     24                           33                      ⋯
chr1_187891_187958      0                            0                      ⋯
chr1_257864_297502     44                           41                      ⋯
chr1_347982_348366      0                            1                      ⋯
chr1_358857_365704      4                            7                      ⋯
chr1_365389_501617     65                          123                      ⋯
chr1_439870_440232      0                            0                      ⋯
chr1_487101_489906      0                            0                      ⋯
chr1_491225_493241      0                            0                      ⋯
chr1_516376_516479      0                            0                      ⋯
chr1_587629_594768      3                            3                      ⋯
chr1_601436_724707     76                           89                      ⋯
⋮                      ⋮                           ⋮                        ⋱
chrY_25813013_25814566 0                            0                       ⋯
chrY_25860943_25861268 0                            0                       ⋯
chrY_25871931_25898653 0                            5                       ⋯
chrY_25904518_25907250 0                            0                       ⋯
chrY_25918323_25918895 0                            0                       ⋯
chrY_25923388_25929826 0                            0                       ⋯
chrY_25928979_25929142 0                            0                       ⋯
chrY_25933833_25935881 0                            0                       ⋯
chrY_25943268_25954152 0                            0                       ⋯
chrY_25975549_25988069 0                            3                       ⋯
chrY_25991241_25991572 0                            0                       ⋯
chrY_25994684_25995697 0                            0                       ⋯
chrY_26002254_26008856 0                            4                       ⋯
chrY_26011435_26012237 0                            0                       ⋯
chrY_26055779_26088493 2                            4                       ⋯
chrY_26123674_26133308 0                            2                       ⋯
chrY_26198331_26208148 0                            2                       ⋯
chrY_26244351_26244573 0                            0                       ⋯
chrY_26247384_26247521 0                            0                       ⋯
chrY_26277923_26354418 2                            9                       ⋯
chrY_26360989_26361092 0                            0                       ⋯
chrY_26400611_26401230 0                            0                       ⋯
chrY_26409815_26420535 0                            2                       ⋯
chrY_26453982_26454092 0                            0                       ⋯
chrY_26508213_26579690 4                           12                       ⋯
chrY_26549425_26549743 0                            0                       ⋯
chrY_26586642_26591601 1                            0                       ⋯
chrY_26594851_26634652 1                            4                       ⋯
chrY_26626520_26627159 0                            0                       ⋯
chrY_56855244_56855488 0                            2                       ⋯
                       17170-P_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409         5
chr1_14404_29570        49
chr1_17369_17436         0
chr1_29554_31109         7
chr1_34554_36081         7
chr1_52473_53312        11
chr1_62948_63887         2
chr1_69091_70008         6
chr1_89295_133723      114
chr1_89551_91105         0
chr1_131025_134836       1
chr1_135141_135895       2
chr1_137682_137965       2
chr1_139790_140339       2
chr1_141474_173862      76
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       9
chr1_184923_200322      49
chr1_187891_187958       0
chr1_257864_297502     136
chr1_347982_348366       0
chr1_358857_365704      17
chr1_365389_501617     397
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       4
chr1_587629_594768      23
chr1_601436_724707     362
⋮                      ⋮
chrY_25813013_25814566  0
chrY_25860943_25861268  0
chrY_25871931_25898653  2
chrY_25904518_25907250  0
chrY_25918323_25918895  0
chrY_25923388_25929826  0
chrY_25928979_25929142  0
chrY_25933833_25935881  0
chrY_25943268_25954152  2
chrY_25975549_25988069  0
chrY_25991241_25991572  0
chrY_25994684_25995697  0
chrY_26002254_26008856  0
chrY_26011435_26012237  0
chrY_26055779_26088493  1
chrY_26123674_26133308  0
chrY_26198331_26208148  1
chrY_26244351_26244573  0
chrY_26247384_26247521  0
chrY_26277923_26354418 11
chrY_26360989_26361092  0
chrY_26400611_26401230  0
chrY_26409815_26420535  0
chrY_26453982_26454092  0
chrY_26508213_26579690  4
chrY_26549425_26549743  0
chrY_26586642_26591601  1
chrY_26594851_26634652  3
chrY_26626520_26627159  0
chrY_56855244_56855488  2

Here counts in Hg38 for H3K27ac samples single end are computed

In [25]:
#Calculate correlation between TSS using Deseq2

library (DESeq2)
library(Rsubread)
#Bam files list where to perform Counts calculation

bamsToCount <- dir("/date/gcb/gcb_MZ/Round1/dedup/picard/SE/H3K27ac/", full.names = TRUE, pattern = "*.\\.bam$")
bamsToCount
# Calculate differential accessibility using DESEQ2


fcResults_SE <- featureCounts(bamsToCount, annot.ext = regionsToCount, isPairedEnd = FALSE,
                           countMultiMappingReads = FALSE, maxFragLength = 100,
                           nthreads = 20)


myCounts_SE <- fcResults$counts

myCounts_SE

[1] "/date/gcb/gcb_MZ/Round1/dedup/picard/SE/H3K27ac//CD19-Roadmap-1_H3K27ac_ChIP-SE.bam"
[2] "/date/gcb/gcb_MZ/Round1/dedup/picard/SE/H3K27ac//CD19-Roadmap-2_H3K27ac_ChIP-SE.bam"
[3] "/date/gcb/gcb_MZ/Round1/dedup/picard/SE/H3K27ac//CD3-Roadmap-1_H3K27ac_ChIP-SE.bam"
[4] "/date/gcb/gcb_MZ/Round1/dedup/picard/SE/H3K27ac//CD3-Roadmap-2_H3K27ac_ChIP-SE.bam"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 2.14.2

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 4 BAM files                                      ||
||                                                                            ||
||                           CD19-Roadmap-1_H3K27ac_ChIP-SE.bam               ||
||                           CD19-Roadmap-2_H3K27ac_ChIP-SE.bam               ||
||                           CD3-Roadmap-1_H3K27ac_ChIP-SE.bam                ||
||                           CD3-Roadmap-2_H3K27ac_ChIP-SE.bam                ||
||                                                                            ||
||              Paired-end : no                                               ||
||        Count read pairs : no                                               ||
||              Annotation : R data.frame                                     ||
||      Dir for temp files : .                                                ||
||                 Threads : 20                                               ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid2658151 ...       ||
||    Features : 59787                                                        ||
||    Meta-features : 59786                                                   ||
||    Chromosomes/contigs : 250                                               ||
||                                                                            ||
|| Process BAM file CD19-Roadmap-1_H3K27ac_ChIP-SE.bam...                     ||
||    Single-end reads are included.                                          ||
||    Total alignments : 14336680                                             ||
||    Successfully assigned alignments : 6286392 (43.8%)                      ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file CD19-Roadmap-2_H3K27ac_ChIP-SE.bam...                     ||
||    Single-end reads are included.                                          ||
||    Total alignments : 18343218                                             ||
||    Successfully assigned alignments : 7960814 (43.4%)                      ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file CD3-Roadmap-1_H3K27ac_ChIP-SE.bam...                      ||
||    Single-end reads are included.                                          ||
||    Total alignments : 12838835                                             ||
||    Successfully assigned alignments : 5995195 (46.7%)                      ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
|| Process BAM file CD3-Roadmap-2_H3K27ac_ChIP-SE.bam...                      ||
||    Single-end reads are included.                                          ||
||    Total alignments : 31635294                                             ||
||    Successfully assigned alignments : 14387103 (45.5%)                     ||
||    Running time : 0.03 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
\\============================================================================//

                       04061-C-100_H3K27ac_ChIP.bam
chr1_11869_14409        1
chr1_14404_29570        1
chr1_17369_17436        0
chr1_29554_31109        0
chr1_34554_36081        0
chr1_52473_53312        0
chr1_62948_63887        0
chr1_69091_70008        0
chr1_89295_133723       4
chr1_89551_91105        0
chr1_131025_134836      0
chr1_135141_135895      0
chr1_137682_137965      0
chr1_139790_140339      0
chr1_141474_173862      2
chr1_157784_157887      0
chr1_160446_161525      0
chr1_182393_184158      0
chr1_184923_200322      3
chr1_187891_187958      0
chr1_257864_297502      7
chr1_347982_348366      0
chr1_358857_365704      2
chr1_365389_501617     21
chr1_439870_440232      0
chr1_487101_489906      0
chr1_491225_493241      0
chr1_516376_516479      0
chr1_587629_594768      0
chr1_601436_724707     12
⋮                      ⋮
chrY_25813013_25814566 0
chrY_25860943_25861268 0
chrY_25871931_25898653 2
chrY_25904518_25907250 0
chrY_25918323_25918895 0
chrY_25923388_25929826 0
chrY_25928979_25929142 0
chrY_25933833_25935881 0
chrY_25943268_25954152 0
chrY_25975549_25988069 1
chrY_25991241_25991572 0
chrY_25994684_25995697 0
chrY_26002254_26008856 0
chrY_26011435_26012237 0
chrY_26055779_26088493 2
chrY_26123674_26133308 1
chrY_26198331_26208148 0
chrY_26244351_26244573 0
chrY_26247384_26247521 0
chrY_26277923_26354418 5
chrY_26360989_26361092 0
chrY_26400611_26401230 0
chrY_26409815_26420535 0
chrY_26453982_26454092 1
chrY_26508213_26579690 1
chrY_26549425_26549743 0
chrY_26586642_26591601 2
chrY_26594851_26634652 3
chrY_26626520_26627159 0
chrY_56855244_56855488 1
                       04061-C-200_H3K27ac_ChIP.bam
chr1_11869_14409        1
chr1_14404_29570        4
chr1_17369_17436        0
chr1_29554_31109        0
chr1_34554_36081        1
chr1_52473_53312        1
chr1_62948_63887        0
chr1_69091_70008        1
chr1_89295_133723      19
chr1_89551_91105        0
chr1_131025_134836      0
chr1_135141_135895      1
chr1_137682_137965      0
chr1_139790_140339      0
chr1_141474_173862     10
chr1_157784_157887      0
chr1_160446_161525      0
chr1_182393_184158      2
chr1_184923_200322      5
chr1_187891_187958      0
chr1_257864_297502     14
chr1_347982_348366      0
chr1_358857_365704      1
chr1_365389_501617     28
chr1_439870_440232      0
chr1_487101_489906      0
chr1_491225_493241      0
chr1_516376_516479      0
chr1_587629_594768      1
chr1_601436_724707     34
⋮                      ⋮
chrY_25813013_25814566 0
chrY_25860943_25861268 0
chrY_25871931_25898653 0
chrY_25904518_25907250 0
chrY_25918323_25918895 0
chrY_25923388_25929826 1
chrY_25928979_25929142 0
chrY_25933833_25935881 0
chrY_25943268_25954152 0
chrY_25975549_25988069 0
chrY_25991241_25991572 0
chrY_25994684_25995697 0
chrY_26002254_26008856 0
chrY_26011435_26012237 0
chrY_26055779_26088493 3
chrY_26123674_26133308 4
chrY_26198331_26208148 1
chrY_26244351_26244573 0
chrY_26247384_26247521 0
chrY_26277923_26354418 5
chrY_26360989_26361092 0
chrY_26400611_26401230 0
chrY_26409815_26420535 1
chrY_26453982_26454092 0
chrY_26508213_26579690 5
chrY_26549425_26549743 0
chrY_26586642_26591601 0
chrY_26594851_26634652 2
chrY_26626520_26627159 0
chrY_56855244_56855488 0
                       04061-P-100_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409         5
chr1_14404_29570         6
chr1_17369_17436         0
chr1_29554_31109         4
chr1_34554_36081         2
chr1_52473_53312         0
chr1_62948_63887         0
chr1_69091_70008         0
chr1_89295_133723       19
chr1_89551_91105         0
chr1_131025_134836       0
chr1_135141_135895       0
chr1_137682_137965       1
chr1_139790_140339       2
chr1_141474_173862      20
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       1
chr1_184923_200322      19
chr1_187891_187958       0
chr1_257864_297502      45
chr1_347982_348366       1
chr1_358857_365704       1
chr1_365389_501617     123
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       0
chr1_587629_594768       4
chr1_601436_724707     102
⋮                      ⋮
chrY_25813013_25814566  0
chrY_25860943_25861268  0
chrY_25871931_25898653  2
chrY_25904518_25907250  0
chrY_25918323_25918895  0
chrY_25923388_25929826  0
chrY_25928979_25929142  0
chrY_25933833_25935881  0
chrY_25943268_25954152  4
chrY_25975549_25988069  3
chrY_25991241_25991572  0
chrY_25994684_25995697  1
chrY_26002254_26008856  0
chrY_26011435_26012237  0
chrY_26055779_26088493  8
chrY_26123674_26133308  0
chrY_26198331_26208148  0
chrY_26244351_26244573  0
chrY_26247384_26247521  0
chrY_26277923_26354418 22
chrY_26360989_26361092  0
chrY_26400611_26401230  0
chrY_26409815_26420535  0
chrY_26453982_26454092  0
chrY_26508213_26579690 14
chrY_26549425_26549743  0
chrY_26586642_26591601  0
chrY_26594851_26634652  9
chrY_26626520_26627159  0
chrY_56855244_56855488  0
                       04061-P-100_H3K27ac_Cut-Tag.bam
chr1_11869_14409         5
chr1_14404_29570         6
chr1_17369_17436         0
chr1_29554_31109         4
chr1_34554_36081         2
chr1_52473_53312         0
chr1_62948_63887         0
chr1_69091_70008         0
chr1_89295_133723       19
chr1_89551_91105         0
chr1_131025_134836       0
chr1_135141_135895       0
chr1_137682_137965       1
chr1_139790_140339       2
chr1_141474_173862      20
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       1
chr1_184923_200322      19
chr1_187891_187958       0
chr1_257864_297502      45
chr1_347982_348366       1
chr1_358857_365704       1
chr1_365389_501617     123
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       0
chr1_587629_594768       4
chr1_601436_724707     102
⋮                      ⋮
chrY_25813013_25814566  0
chrY_25860943_25861268  0
chrY_25871931_25898653  2
chrY_25904518_25907250  0
chrY_25918323_25918895  0
chrY_25923388_25929826  0
chrY_25928979_25929142  0
chrY_25933833_25935881  0
chrY_25943268_25954152  4
chrY_25975549_25988069  3
chrY_25991241_25991572  0
chrY_25994684_25995697  1
chrY_26002254_26008856  0
chrY_26011435_26012237  0
chrY_26055779_26088493  8
chrY_26123674_26133308  0
chrY_26198331_26208148  0
chrY_26244351_26244573  0
chrY_26247384_26247521  0
chrY_26277923_26354418 22
chrY_26360989_26361092  0
chrY_26400611_26401230  0
chrY_26409815_26420535  0
chrY_26453982_26454092  0
chrY_26508213_26579690 14
chrY_26549425_26549743  0
chrY_26586642_26591601  0
chrY_26594851_26634652  9
chrY_26626520_26627159  0
chrY_56855244_56855488  0
                       04061-P-200_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409         4
chr1_14404_29570        35
chr1_17369_17436         0
chr1_29554_31109        16
chr1_34554_36081         0
chr1_52473_53312         0
chr1_62948_63887         0
chr1_69091_70008         6
chr1_89295_133723       94
chr1_89551_91105         0
chr1_131025_134836       2
chr1_135141_135895       3
chr1_137682_137965       0
chr1_139790_140339       1
chr1_141474_173862      37
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       7
chr1_184923_200322      56
chr1_187891_187958       0
chr1_257864_297502      91
chr1_347982_348366       3
chr1_358857_365704       9
chr1_365389_501617     488
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       0
chr1_587629_594768       5
chr1_601436_724707     304
⋮                      ⋮
chrY_25813013_25814566   4
chrY_25860943_25861268   0
chrY_25871931_25898653  18
chrY_25904518_25907250   1
chrY_25918323_25918895   0
chrY_25923388_25929826   4
chrY_25928979_25929142   0
chrY_25933833_25935881   1
chrY_25943268_25954152   2
chrY_25975549_25988069   5
chrY_25991241_25991572   0
chrY_25994684_25995697   0
chrY_26002254_26008856  21
chrY_26011435_26012237   0
chrY_26055779_26088493  35
chrY_26123674_26133308   6
chrY_26198331_26208148   2
chrY_26244351_26244573   0
chrY_26247384_26247521   0
chrY_26277923_26354418 129
chrY_26360989_26361092   0
chrY_26400611_26401230   0
chrY_26409815_26420535   2
chrY_26453982_26454092   1
chrY_26508213_26579690  62
chrY_26549425_26549743   0
chrY_26586642_26591601  13
chrY_26594851_26634652  43
chrY_26626520_26627159   0
chrY_56855244_56855488   1
                       04061-P-200_H3K27ac_Cut-Tag.bam 12097-C_H3K27ac_ChIP.bam
chr1_11869_14409         4                              2
chr1_14404_29570        35                              9
chr1_17369_17436         0                              0
chr1_29554_31109        16                              0
chr1_34554_36081         0                              2
chr1_52473_53312         0                              1
chr1_62948_63887         0                              0
chr1_69091_70008         6                              0
chr1_89295_133723       94                             37
chr1_89551_91105         0                              0
chr1_131025_134836       2                              0
chr1_135141_135895       3                              0
chr1_137682_137965       0                              0
chr1_139790_140339       1                              0
chr1_141474_173862      37                             15
chr1_157784_157887       0                              0
chr1_160446_161525       0                              0
chr1_182393_184158       7                              2
chr1_184923_200322      56                              9
chr1_187891_187958       0                              0
chr1_257864_297502      91                             36
chr1_347982_348366       3                              0
chr1_358857_365704       9                              3
chr1_365389_501617     488                             62
chr1_439870_440232       0                              0
chr1_487101_489906       0                              0
chr1_491225_493241       0                              0
chr1_516376_516479       0                              0
chr1_587629_594768       5                              1
chr1_601436_724707     304                             62
⋮                      ⋮                               ⋮
chrY_25813013_25814566   4                             0
chrY_25860943_25861268   0                             0
chrY_25871931_25898653  18                             4
chrY_25904518_25907250   1                             0
chrY_25918323_25918895   0                             0
chrY_25923388_25929826   4                             0
chrY_25928979_25929142   0                             0
chrY_25933833_25935881   1                             0
chrY_25943268_25954152   2                             3
chrY_25975549_25988069   5                             1
chrY_25991241_25991572   0                             0
chrY_25994684_25995697   0                             0
chrY_26002254_26008856  21                             2
chrY_26011435_26012237   0                             0
chrY_26055779_26088493  35                             3
chrY_26123674_26133308   6                             1
chrY_26198331_26208148   2                             2
chrY_26244351_26244573   0                             0
chrY_26247384_26247521   0                             0
chrY_26277923_26354418 129                             5
chrY_26360989_26361092   0                             0
chrY_26400611_26401230   0                             0
chrY_26409815_26420535   2                             3
chrY_26453982_26454092   1                             0
chrY_26508213_26579690  62                             9
chrY_26549425_26549743   0                             0
chrY_26586642_26591601  13                             0
chrY_26594851_26634652  43                             6
chrY_26626520_26627159   0                             0
chrY_56855244_56855488   1                             0
                       12097-C_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409        2
chr1_14404_29570       23
chr1_17369_17436        0
chr1_29554_31109        1
chr1_34554_36081        2
chr1_52473_53312        2
chr1_62948_63887        0
chr1_69091_70008        0
chr1_89295_133723      19
chr1_89551_91105        0
chr1_131025_134836      1
chr1_135141_135895      1
chr1_137682_137965      0
chr1_139790_140339      1
chr1_141474_173862     16
chr1_157784_157887      0
chr1_160446_161525      0
chr1_182393_184158      0
chr1_184923_200322     24
chr1_187891_187958      0
chr1_257864_297502     44
chr1_347982_348366      0
chr1_358857_365704      4
chr1_365389_501617     65
chr1_439870_440232      0
chr1_487101_489906      0
chr1_491225_493241      0
chr1_516376_516479      0
chr1_587629_594768      3
chr1_601436_724707     76
⋮                      ⋮
chrY_25813013_25814566 0
chrY_25860943_25861268 0
chrY_25871931_25898653 0
chrY_25904518_25907250 0
chrY_25918323_25918895 0
chrY_25923388_25929826 0
chrY_25928979_25929142 0
chrY_25933833_25935881 0
chrY_25943268_25954152 0
chrY_25975549_25988069 0
chrY_25991241_25991572 0
chrY_25994684_25995697 0
chrY_26002254_26008856 0
chrY_26011435_26012237 0
chrY_26055779_26088493 2
chrY_26123674_26133308 0
chrY_26198331_26208148 0
chrY_26244351_26244573 0
chrY_26247384_26247521 0
chrY_26277923_26354418 2
chrY_26360989_26361092 0
chrY_26400611_26401230 0
chrY_26409815_26420535 0
chrY_26453982_26454092 0
chrY_26508213_26579690 4
chrY_26549425_26549743 0
chrY_26586642_26591601 1
chrY_26594851_26634652 1
chrY_26626520_26627159 0
chrY_56855244_56855488 0
                       12097-C_H3K27ac_Cut-Tag.bam 12097-P_H3K27ac_ChIP.bam ⋯
chr1_11869_14409        2                            5                      ⋯
chr1_14404_29570       23                           27                      ⋯
chr1_17369_17436        0                            0                      ⋯
chr1_29554_31109        1                            5                      ⋯
chr1_34554_36081        2                            2                      ⋯
chr1_52473_53312        2                            1                      ⋯
chr1_62948_63887        0                            0                      ⋯
chr1_69091_70008        0                            0                      ⋯
chr1_89295_133723      19                           46                      ⋯
chr1_89551_91105        0                            0                      ⋯
chr1_131025_134836      1                            3                      ⋯
chr1_135141_135895      1                            0                      ⋯
chr1_137682_137965      0                            3                      ⋯
chr1_139790_140339      1                            0                      ⋯
chr1_141474_173862     16                           23                      ⋯
chr1_157784_157887      0                            0                      ⋯
chr1_160446_161525      0                            0                      ⋯
chr1_182393_184158      0                            3                      ⋯
chr1_184923_200322     24                           33                      ⋯
chr1_187891_187958      0                            0                      ⋯
chr1_257864_297502     44                           41                      ⋯
chr1_347982_348366      0                            1                      ⋯
chr1_358857_365704      4                            7                      ⋯
chr1_365389_501617     65                          123                      ⋯
chr1_439870_440232      0                            0                      ⋯
chr1_487101_489906      0                            0                      ⋯
chr1_491225_493241      0                            0                      ⋯
chr1_516376_516479      0                            0                      ⋯
chr1_587629_594768      3                            3                      ⋯
chr1_601436_724707     76                           89                      ⋯
⋮                      ⋮                           ⋮                        ⋱
chrY_25813013_25814566 0                            0                       ⋯
chrY_25860943_25861268 0                            0                       ⋯
chrY_25871931_25898653 0                            5                       ⋯
chrY_25904518_25907250 0                            0                       ⋯
chrY_25918323_25918895 0                            0                       ⋯
chrY_25923388_25929826 0                            0                       ⋯
chrY_25928979_25929142 0                            0                       ⋯
chrY_25933833_25935881 0                            0                       ⋯
chrY_25943268_25954152 0                            0                       ⋯
chrY_25975549_25988069 0                            3                       ⋯
chrY_25991241_25991572 0                            0                       ⋯
chrY_25994684_25995697 0                            0                       ⋯
chrY_26002254_26008856 0                            4                       ⋯
chrY_26011435_26012237 0                            0                       ⋯
chrY_26055779_26088493 2                            4                       ⋯
chrY_26123674_26133308 0                            2                       ⋯
chrY_26198331_26208148 0                            2                       ⋯
chrY_26244351_26244573 0                            0                       ⋯
chrY_26247384_26247521 0                            0                       ⋯
chrY_26277923_26354418 2                            9                       ⋯
chrY_26360989_26361092 0                            0                       ⋯
chrY_26400611_26401230 0                            0                       ⋯
chrY_26409815_26420535 0                            2                       ⋯
chrY_26453982_26454092 0                            0                       ⋯
chrY_26508213_26579690 4                           12                       ⋯
chrY_26549425_26549743 0                            0                       ⋯
chrY_26586642_26591601 1                            0                       ⋯
chrY_26594851_26634652 1                            4                       ⋯
chrY_26626520_26627159 0                            0                       ⋯
chrY_56855244_56855488 0                            2                       ⋯
                       17170-P_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409         5
chr1_14404_29570        49
chr1_17369_17436         0
chr1_29554_31109         7
chr1_34554_36081         7
chr1_52473_53312        11
chr1_62948_63887         2
chr1_69091_70008         6
chr1_89295_133723      114
chr1_89551_91105         0
chr1_131025_134836       1
chr1_135141_135895       2
chr1_137682_137965       2
chr1_139790_140339       2
chr1_141474_173862      76
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       9
chr1_184923_200322      49
chr1_187891_187958       0
chr1_257864_297502     136
chr1_347982_348366       0
chr1_358857_365704      17
chr1_365389_501617     397
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       4
chr1_587629_594768      23
chr1_601436_724707     362
⋮                      ⋮
chrY_25813013_25814566  0
chrY_25860943_25861268  0
chrY_25871931_25898653  2
chrY_25904518_25907250  0
chrY_25918323_25918895  0
chrY_25923388_25929826  0
chrY_25928979_25929142  0
chrY_25933833_25935881  0
chrY_25943268_25954152  2
chrY_25975549_25988069  0
chrY_25991241_25991572  0
chrY_25994684_25995697  0
chrY_26002254_26008856  0
chrY_26011435_26012237  0
chrY_26055779_26088493  1
chrY_26123674_26133308  0
chrY_26198331_26208148  1
chrY_26244351_26244573  0
chrY_26247384_26247521  0
chrY_26277923_26354418 11
chrY_26360989_26361092  0
chrY_26400611_26401230  0
chrY_26409815_26420535  0
chrY_26453982_26454092  0
chrY_26508213_26579690  4
chrY_26549425_26549743  0
chrY_26586642_26591601  1
chrY_26594851_26634652  3
chrY_26626520_26627159  0
chrY_56855244_56855488  2

The two matrices now will be bound together to build a unique matrix

In [26]:
myCounts <- cbind(myCounts_PE,myCounts_SE)

myCounts

# Remove ".bam" from column names using sub()
colnames(myCounts) <- sub("\\.bam$", "", colnames(myCounts))

# Check the updated column names
print(colnames(myCounts))

Group<-colnames(myCounts)
replicates <- colnames(myCounts)

metaData<- data.frame(Group=Group,replicates=replicates)
metaData

                       04061-C-100_H3K27ac_ChIP.bam
chr1_11869_14409        1
chr1_14404_29570        1
chr1_17369_17436        0
chr1_29554_31109        0
chr1_34554_36081        0
chr1_52473_53312        0
chr1_62948_63887        0
chr1_69091_70008        0
chr1_89295_133723       4
chr1_89551_91105        0
chr1_131025_134836      0
chr1_135141_135895      0
chr1_137682_137965      0
chr1_139790_140339      0
chr1_141474_173862      2
chr1_157784_157887      0
chr1_160446_161525      0
chr1_182393_184158      0
chr1_184923_200322      3
chr1_187891_187958      0
chr1_257864_297502      7
chr1_347982_348366      0
chr1_358857_365704      2
chr1_365389_501617     21
chr1_439870_440232      0
chr1_487101_489906      0
chr1_491225_493241      0
chr1_516376_516479      0
chr1_587629_594768      0
chr1_601436_724707     12
⋮                      ⋮
chrY_25813013_25814566 0
chrY_25860943_25861268 0
chrY_25871931_25898653 2
chrY_25904518_25907250 0
chrY_25918323_25918895 0
chrY_25923388_25929826 0
chrY_25928979_25929142 0
chrY_25933833_25935881 0
chrY_25943268_25954152 0
chrY_25975549_25988069 1
chrY_25991241_25991572 0
chrY_25994684_25995697 0
chrY_26002254_26008856 0
chrY_26011435_26012237 0
chrY_26055779_26088493 2
chrY_26123674_26133308 1
chrY_26198331_26208148 0
chrY_26244351_26244573 0
chrY_26247384_26247521 0
chrY_26277923_26354418 5
chrY_26360989_26361092 0
chrY_26400611_26401230 0
chrY_26409815_26420535 0
chrY_26453982_26454092 1
chrY_26508213_26579690 1
chrY_26549425_26549743 0
chrY_26586642_26591601 2
chrY_26594851_26634652 3
chrY_26626520_26627159 0
chrY_56855244_56855488 1
                       04061-C-200_H3K27ac_ChIP.bam
chr1_11869_14409        1
chr1_14404_29570        4
chr1_17369_17436        0
chr1_29554_31109        0
chr1_34554_36081        1
chr1_52473_53312        1
chr1_62948_63887        0
chr1_69091_70008        1
chr1_89295_133723      19
chr1_89551_91105        0
chr1_131025_134836      0
chr1_135141_135895      1
chr1_137682_137965      0
chr1_139790_140339      0
chr1_141474_173862     10
chr1_157784_157887      0
chr1_160446_161525      0
chr1_182393_184158      2
chr1_184923_200322      5
chr1_187891_187958      0
chr1_257864_297502     14
chr1_347982_348366      0
chr1_358857_365704      1
chr1_365389_501617     28
chr1_439870_440232      0
chr1_487101_489906      0
chr1_491225_493241      0
chr1_516376_516479      0
chr1_587629_594768      1
chr1_601436_724707     34
⋮                      ⋮
chrY_25813013_25814566 0
chrY_25860943_25861268 0
chrY_25871931_25898653 0
chrY_25904518_25907250 0
chrY_25918323_25918895 0
chrY_25923388_25929826 1
chrY_25928979_25929142 0
chrY_25933833_25935881 0
chrY_25943268_25954152 0
chrY_25975549_25988069 0
chrY_25991241_25991572 0
chrY_25994684_25995697 0
chrY_26002254_26008856 0
chrY_26011435_26012237 0
chrY_26055779_26088493 3
chrY_26123674_26133308 4
chrY_26198331_26208148 1
chrY_26244351_26244573 0
chrY_26247384_26247521 0
chrY_26277923_26354418 5
chrY_26360989_26361092 0
chrY_26400611_26401230 0
chrY_26409815_26420535 1
chrY_26453982_26454092 0
chrY_26508213_26579690 5
chrY_26549425_26549743 0
chrY_26586642_26591601 0
chrY_26594851_26634652 2
chrY_26626520_26627159 0
chrY_56855244_56855488 0
                       04061-P-100_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409         5
chr1_14404_29570         6
chr1_17369_17436         0
chr1_29554_31109         4
chr1_34554_36081         2
chr1_52473_53312         0
chr1_62948_63887         0
chr1_69091_70008         0
chr1_89295_133723       19
chr1_89551_91105         0
chr1_131025_134836       0
chr1_135141_135895       0
chr1_137682_137965       1
chr1_139790_140339       2
chr1_141474_173862      20
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       1
chr1_184923_200322      19
chr1_187891_187958       0
chr1_257864_297502      45
chr1_347982_348366       1
chr1_358857_365704       1
chr1_365389_501617     123
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       0
chr1_587629_594768       4
chr1_601436_724707     102
⋮                      ⋮
chrY_25813013_25814566  0
chrY_25860943_25861268  0
chrY_25871931_25898653  2
chrY_25904518_25907250  0
chrY_25918323_25918895  0
chrY_25923388_25929826  0
chrY_25928979_25929142  0
chrY_25933833_25935881  0
chrY_25943268_25954152  4
chrY_25975549_25988069  3
chrY_25991241_25991572  0
chrY_25994684_25995697  1
chrY_26002254_26008856  0
chrY_26011435_26012237  0
chrY_26055779_26088493  8
chrY_26123674_26133308  0
chrY_26198331_26208148  0
chrY_26244351_26244573  0
chrY_26247384_26247521  0
chrY_26277923_26354418 22
chrY_26360989_26361092  0
chrY_26400611_26401230  0
chrY_26409815_26420535  0
chrY_26453982_26454092  0
chrY_26508213_26579690 14
chrY_26549425_26549743  0
chrY_26586642_26591601  0
chrY_26594851_26634652  9
chrY_26626520_26627159  0
chrY_56855244_56855488  0
                       04061-P-100_H3K27ac_Cut-Tag.bam
chr1_11869_14409         5
chr1_14404_29570         6
chr1_17369_17436         0
chr1_29554_31109         4
chr1_34554_36081         2
chr1_52473_53312         0
chr1_62948_63887         0
chr1_69091_70008         0
chr1_89295_133723       19
chr1_89551_91105         0
chr1_131025_134836       0
chr1_135141_135895       0
chr1_137682_137965       1
chr1_139790_140339       2
chr1_141474_173862      20
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       1
chr1_184923_200322      19
chr1_187891_187958       0
chr1_257864_297502      45
chr1_347982_348366       1
chr1_358857_365704       1
chr1_365389_501617     123
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       0
chr1_587629_594768       4
chr1_601436_724707     102
⋮                      ⋮
chrY_25813013_25814566  0
chrY_25860943_25861268  0
chrY_25871931_25898653  2
chrY_25904518_25907250  0
chrY_25918323_25918895  0
chrY_25923388_25929826  0
chrY_25928979_25929142  0
chrY_25933833_25935881  0
chrY_25943268_25954152  4
chrY_25975549_25988069  3
chrY_25991241_25991572  0
chrY_25994684_25995697  1
chrY_26002254_26008856  0
chrY_26011435_26012237  0
chrY_26055779_26088493  8
chrY_26123674_26133308  0
chrY_26198331_26208148  0
chrY_26244351_26244573  0
chrY_26247384_26247521  0
chrY_26277923_26354418 22
chrY_26360989_26361092  0
chrY_26400611_26401230  0
chrY_26409815_26420535  0
chrY_26453982_26454092  0
chrY_26508213_26579690 14
chrY_26549425_26549743  0
chrY_26586642_26591601  0
chrY_26594851_26634652  9
chrY_26626520_26627159  0
chrY_56855244_56855488  0
                       04061-P-200_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409         4
chr1_14404_29570        35
chr1_17369_17436         0
chr1_29554_31109        16
chr1_34554_36081         0
chr1_52473_53312         0
chr1_62948_63887         0
chr1_69091_70008         6
chr1_89295_133723       94
chr1_89551_91105         0
chr1_131025_134836       2
chr1_135141_135895       3
chr1_137682_137965       0
chr1_139790_140339       1
chr1_141474_173862      37
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       7
chr1_184923_200322      56
chr1_187891_187958       0
chr1_257864_297502      91
chr1_347982_348366       3
chr1_358857_365704       9
chr1_365389_501617     488
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       0
chr1_587629_594768       5
chr1_601436_724707     304
⋮                      ⋮
chrY_25813013_25814566   4
chrY_25860943_25861268   0
chrY_25871931_25898653  18
chrY_25904518_25907250   1
chrY_25918323_25918895   0
chrY_25923388_25929826   4
chrY_25928979_25929142   0
chrY_25933833_25935881   1
chrY_25943268_25954152   2
chrY_25975549_25988069   5
chrY_25991241_25991572   0
chrY_25994684_25995697   0
chrY_26002254_26008856  21
chrY_26011435_26012237   0
chrY_26055779_26088493  35
chrY_26123674_26133308   6
chrY_26198331_26208148   2
chrY_26244351_26244573   0
chrY_26247384_26247521   0
chrY_26277923_26354418 129
chrY_26360989_26361092   0
chrY_26400611_26401230   0
chrY_26409815_26420535   2
chrY_26453982_26454092   1
chrY_26508213_26579690  62
chrY_26549425_26549743   0
chrY_26586642_26591601  13
chrY_26594851_26634652  43
chrY_26626520_26627159   0
chrY_56855244_56855488   1
                       04061-P-200_H3K27ac_Cut-Tag.bam 12097-C_H3K27ac_ChIP.bam
chr1_11869_14409         4                              2
chr1_14404_29570        35                              9
chr1_17369_17436         0                              0
chr1_29554_31109        16                              0
chr1_34554_36081         0                              2
chr1_52473_53312         0                              1
chr1_62948_63887         0                              0
chr1_69091_70008         6                              0
chr1_89295_133723       94                             37
chr1_89551_91105         0                              0
chr1_131025_134836       2                              0
chr1_135141_135895       3                              0
chr1_137682_137965       0                              0
chr1_139790_140339       1                              0
chr1_141474_173862      37                             15
chr1_157784_157887       0                              0
chr1_160446_161525       0                              0
chr1_182393_184158       7                              2
chr1_184923_200322      56                              9
chr1_187891_187958       0                              0
chr1_257864_297502      91                             36
chr1_347982_348366       3                              0
chr1_358857_365704       9                              3
chr1_365389_501617     488                             62
chr1_439870_440232       0                              0
chr1_487101_489906       0                              0
chr1_491225_493241       0                              0
chr1_516376_516479       0                              0
chr1_587629_594768       5                              1
chr1_601436_724707     304                             62
⋮                      ⋮                               ⋮
chrY_25813013_25814566   4                             0
chrY_25860943_25861268   0                             0
chrY_25871931_25898653  18                             4
chrY_25904518_25907250   1                             0
chrY_25918323_25918895   0                             0
chrY_25923388_25929826   4                             0
chrY_25928979_25929142   0                             0
chrY_25933833_25935881   1                             0
chrY_25943268_25954152   2                             3
chrY_25975549_25988069   5                             1
chrY_25991241_25991572   0                             0
chrY_25994684_25995697   0                             0
chrY_26002254_26008856  21                             2
chrY_26011435_26012237   0                             0
chrY_26055779_26088493  35                             3
chrY_26123674_26133308   6                             1
chrY_26198331_26208148   2                             2
chrY_26244351_26244573   0                             0
chrY_26247384_26247521   0                             0
chrY_26277923_26354418 129                             5
chrY_26360989_26361092   0                             0
chrY_26400611_26401230   0                             0
chrY_26409815_26420535   2                             3
chrY_26453982_26454092   1                             0
chrY_26508213_26579690  62                             9
chrY_26549425_26549743   0                             0
chrY_26586642_26591601  13                             0
chrY_26594851_26634652  43                             6
chrY_26626520_26627159   0                             0
chrY_56855244_56855488   1                             0
                       12097-C_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409        2
chr1_14404_29570       23
chr1_17369_17436        0
chr1_29554_31109        1
chr1_34554_36081        2
chr1_52473_53312        2
chr1_62948_63887        0
chr1_69091_70008        0
chr1_89295_133723      19
chr1_89551_91105        0
chr1_131025_134836      1
chr1_135141_135895      1
chr1_137682_137965      0
chr1_139790_140339      1
chr1_141474_173862     16
chr1_157784_157887      0
chr1_160446_161525      0
chr1_182393_184158      0
chr1_184923_200322     24
chr1_187891_187958      0
chr1_257864_297502     44
chr1_347982_348366      0
chr1_358857_365704      4
chr1_365389_501617     65
chr1_439870_440232      0
chr1_487101_489906      0
chr1_491225_493241      0
chr1_516376_516479      0
chr1_587629_594768      3
chr1_601436_724707     76
⋮                      ⋮
chrY_25813013_25814566 0
chrY_25860943_25861268 0
chrY_25871931_25898653 0
chrY_25904518_25907250 0
chrY_25918323_25918895 0
chrY_25923388_25929826 0
chrY_25928979_25929142 0
chrY_25933833_25935881 0
chrY_25943268_25954152 0
chrY_25975549_25988069 0
chrY_25991241_25991572 0
chrY_25994684_25995697 0
chrY_26002254_26008856 0
chrY_26011435_26012237 0
chrY_26055779_26088493 2
chrY_26123674_26133308 0
chrY_26198331_26208148 0
chrY_26244351_26244573 0
chrY_26247384_26247521 0
chrY_26277923_26354418 2
chrY_26360989_26361092 0
chrY_26400611_26401230 0
chrY_26409815_26420535 0
chrY_26453982_26454092 0
chrY_26508213_26579690 4
chrY_26549425_26549743 0
chrY_26586642_26591601 1
chrY_26594851_26634652 1
chrY_26626520_26627159 0
chrY_56855244_56855488 0
                       12097-C_H3K27ac_Cut-Tag.bam 12097-P_H3K27ac_ChIP.bam ⋯
chr1_11869_14409        2                            5                      ⋯
chr1_14404_29570       23                           27                      ⋯
chr1_17369_17436        0                            0                      ⋯
chr1_29554_31109        1                            5                      ⋯
chr1_34554_36081        2                            2                      ⋯
chr1_52473_53312        2                            1                      ⋯
chr1_62948_63887        0                            0                      ⋯
chr1_69091_70008        0                            0                      ⋯
chr1_89295_133723      19                           46                      ⋯
chr1_89551_91105        0                            0                      ⋯
chr1_131025_134836      1                            3                      ⋯
chr1_135141_135895      1                            0                      ⋯
chr1_137682_137965      0                            3                      ⋯
chr1_139790_140339      1                            0                      ⋯
chr1_141474_173862     16                           23                      ⋯
chr1_157784_157887      0                            0                      ⋯
chr1_160446_161525      0                            0                      ⋯
chr1_182393_184158      0                            3                      ⋯
chr1_184923_200322     24                           33                      ⋯
chr1_187891_187958      0                            0                      ⋯
chr1_257864_297502     44                           41                      ⋯
chr1_347982_348366      0                            1                      ⋯
chr1_358857_365704      4                            7                      ⋯
chr1_365389_501617     65                          123                      ⋯
chr1_439870_440232      0                            0                      ⋯
chr1_487101_489906      0                            0                      ⋯
chr1_491225_493241      0                            0                      ⋯
chr1_516376_516479      0                            0                      ⋯
chr1_587629_594768      3                            3                      ⋯
chr1_601436_724707     76                           89                      ⋯
⋮                      ⋮                           ⋮                        ⋱
chrY_25813013_25814566 0                            0                       ⋯
chrY_25860943_25861268 0                            0                       ⋯
chrY_25871931_25898653 0                            5                       ⋯
chrY_25904518_25907250 0                            0                       ⋯
chrY_25918323_25918895 0                            0                       ⋯
chrY_25923388_25929826 0                            0                       ⋯
chrY_25928979_25929142 0                            0                       ⋯
chrY_25933833_25935881 0                            0                       ⋯
chrY_25943268_25954152 0                            0                       ⋯
chrY_25975549_25988069 0                            3                       ⋯
chrY_25991241_25991572 0                            0                       ⋯
chrY_25994684_25995697 0                            0                       ⋯
chrY_26002254_26008856 0                            4                       ⋯
chrY_26011435_26012237 0                            0                       ⋯
chrY_26055779_26088493 2                            4                       ⋯
chrY_26123674_26133308 0                            2                       ⋯
chrY_26198331_26208148 0                            2                       ⋯
chrY_26244351_26244573 0                            0                       ⋯
chrY_26247384_26247521 0                            0                       ⋯
chrY_26277923_26354418 2                            9                       ⋯
chrY_26360989_26361092 0                            0                       ⋯
chrY_26400611_26401230 0                            0                       ⋯
chrY_26409815_26420535 0                            2                       ⋯
chrY_26453982_26454092 0                            0                       ⋯
chrY_26508213_26579690 4                           12                       ⋯
chrY_26549425_26549743 0                            0                       ⋯
chrY_26586642_26591601 1                            0                       ⋯
chrY_26594851_26634652 1                            4                       ⋯
chrY_26626520_26627159 0                            0                       ⋯
chrY_56855244_56855488 0                            2                       ⋯
                       17170-P_H3K27ac_Cut-Tag_broad.bam
chr1_11869_14409         5
chr1_14404_29570        49
chr1_17369_17436         0
chr1_29554_31109         7
chr1_34554_36081         7
chr1_52473_53312        11
chr1_62948_63887         2
chr1_69091_70008         6
chr1_89295_133723      114
chr1_89551_91105         0
chr1_131025_134836       1
chr1_135141_135895       2
chr1_137682_137965       2
chr1_139790_140339       2
chr1_141474_173862      76
chr1_157784_157887       0
chr1_160446_161525       0
chr1_182393_184158       9
chr1_184923_200322      49
chr1_187891_187958       0
chr1_257864_297502     136
chr1_347982_348366       0
chr1_358857_365704      17
chr1_365389_501617     397
chr1_439870_440232       0
chr1_487101_489906       0
chr1_491225_493241       0
chr1_516376_516479       4
chr1_587629_594768      23
chr1_601436_724707     362
⋮                      ⋮
chrY_25813013_25814566  0
chrY_25860943_25861268  0
chrY_25871931_25898653  2
chrY_25904518_25907250  0
chrY_25918323_25918895  0
chrY_25923388_25929826  0
chrY_25928979_25929142  0
chrY_25933833_25935881  0
chrY_25943268_25954152  2
chrY_25975549_25988069  0
chrY_25991241_25991572  0
chrY_25994684_25995697  0
chrY_26002254_26008856  0
chrY_26011435_26012237  0
chrY_26055779_26088493  1
chrY_26123674_26133308  0
chrY_26198331_26208148  1
chrY_26244351_26244573  0
chrY_26247384_26247521  0
chrY_26277923_26354418 11
chrY_26360989_26361092  0
chrY_26400611_26401230  0
chrY_26409815_26420535  0
chrY_26453982_26454092  0
chrY_26508213_26579690  4
chrY_26549425_26549743  0
chrY_26586642_26591601  1
chrY_26594851_26634652  3
chrY_26626520_26627159  0
chrY_56855244_56855488  2

 [1] "04061-C-100_H3K27ac_ChIP"          "04061-C-200_H3K27ac_ChIP"
 [3] "04061-P-100_H3K27ac_Cut-Tag_broad" "04061-P-100_H3K27ac_Cut-Tag"
 [5] "04061-P-200_H3K27ac_Cut-Tag_broad" "04061-P-200_H3K27ac_Cut-Tag"
 [7] "12097-C_H3K27ac_ChIP"              "12097-C_H3K27ac_Cut-Tag_broad"
 [9] "12097-C_H3K27ac_Cut-Tag"           "12097-P_H3K27ac_ChIP"
[11] "14223-C_H3K27ac_ChIP"              "14223-C_H3K27ac_Cut-Tag_broad"
[13] "14223-C_H3K27ac_Cut-Tag"           "14223-P_H3K27ac_ChIP"
[15] "14223-P_H3K27ac_Cut-Tag_broad"     "14223-P_H3K27ac_Cut-Tag"
[17] "16057-P-100_H3K27ac_ChIP"          "16057-P-100_H3K27ac_Cut-Tag_broad"
[19] "16057-P-100_H3K27ac_Cut-Tag"       "16057-P-200_H3K27ac_ChIP"
[21] "16057-P-200_H3K27ac_Cut-Tag_broad" "16057-P-200_H3K27ac_Cut-Tag"
[23] "16170-C_H3K27ac_ChIP"              "16170-P_H3K27ac_ChIP"
[25] "17170-P_H3K27ac_Cut-Tag_broad"     "17170-P_H3K27ac_Cut-Tag"
[27] "19019-C_H3K27ac_ChIP"              "19019-C_H3K27ac_Cut-Tag_broad"
[29] "19019-C_H3K27ac_Cut-Tag"           "19019-P_H3K27ac_ChIP"
[31] "19019-P_H3K27ac_Cut-Tag_broad"     "19019-P_H3K27ac_Cut-Tag"
[33] "CD19-GSE172116-1_H3K27ac_ChIP"     "CD19-GSE172116-2_H3K27ac_ChIP"
[35] "04061-C-100_H3K27ac_ChIP"          "04061-C-200_H3K27ac_ChIP"
[37] "04061-P-100_H3K27ac_Cut-Tag_broad" "04061-P-100_H3K27ac_Cut-Tag"
[39] "04061-P-200_H3K27ac_Cut-Tag_broad" "04061-P-200_H3K27ac_Cut-Tag"
[41] "12097-C_H3K27ac_ChIP"              "12097-C_H3K27ac_Cut-Tag_broad"
[43] "12097-C_H3K27ac_Cut-Tag"           "12097-P_H3K27ac_ChIP"
[45] "14223-C_H3K27ac_ChIP"              "14223-C_H3K27ac_Cut-Tag_broad"
[47] "14223-C_H3K27ac_Cut-Tag"           "14223-P_H3K27ac_ChIP"
[49] "14223-P_H3K27ac_Cut-Tag_broad"     "14223-P_H3K27ac_Cut-Tag"
[51] "16057-P-100_H3K27ac_ChIP"          "16057-P-100_H3K27ac_Cut-Tag_broad"
[53] "16057-P-100_H3K27ac_Cut-Tag"       "16057-P-200_H3K27ac_ChIP"
[55] "16057-P-200_H3K27ac_Cut-Tag_broad" "16057-P-200_H3K27ac_Cut-Tag"
[57] "16170-C_H3K27ac_ChIP"              "16170-P_H3K27ac_ChIP"
[59] "17170-P_H3K27ac_Cut-Tag_broad"     "17170-P_H3K27ac_Cut-Tag"
[61] "19019-C_H3K27ac_ChIP"              "19019-C_H3K27ac_Cut-Tag_broad"
[63] "19019-C_H3K27ac_Cut-Tag"           "19019-P_H3K27ac_ChIP"
[65] "19019-P_H3K27ac_Cut-Tag_broad"     "19019-P_H3K27ac_Cut-Tag"
[67] "CD19-GSE172116-1_H3K27ac_ChIP"     "CD19-GSE172116-2_H3K27ac_ChIP"

   Group                             replicates
1  04061-C-100_H3K27ac_ChIP          04061-C-100_H3K27ac_ChIP
2  04061-C-200_H3K27ac_ChIP          04061-C-200_H3K27ac_ChIP
3  04061-P-100_H3K27ac_Cut-Tag_broad 04061-P-100_H3K27ac_Cut-Tag_broad
4  04061-P-100_H3K27ac_Cut-Tag       04061-P-100_H3K27ac_Cut-Tag
5  04061-P-200_H3K27ac_Cut-Tag_broad 04061-P-200_H3K27ac_Cut-Tag_broad
6  04061-P-200_H3K27ac_Cut-Tag       04061-P-200_H3K27ac_Cut-Tag
7  12097-C_H3K27ac_ChIP              12097-C_H3K27ac_ChIP
8  12097-C_H3K27ac_Cut-Tag_broad     12097-C_H3K27ac_Cut-Tag_broad
9  12097-C_H3K27ac_Cut-Tag           12097-C_H3K27ac_Cut-Tag
10 12097-P_H3K27ac_ChIP              12097-P_H3K27ac_ChIP
11 14223-C_H3K27ac_ChIP              14223-C_H3K27ac_ChIP
12 14223-C_H3K27ac_Cut-Tag_broad     14223-C_H3K27ac_Cut-Tag_broad
13 14223-C_H3K27ac_Cut-Tag           14223-C_H3K27ac_Cut-Tag
14 14223-P_H3K27ac_ChIP              14223-P_H3K27ac_ChIP
15 14223-P_H3K27ac_Cut-Tag_broad     14223-P_H3K27ac_Cut-Tag_broad
16 14223-P_H3K27ac_Cut-Tag           14223-P_H3K27ac_Cut-Tag
17 16057-P-100_H3K27ac_ChIP          16057-P-100_H3K27ac_ChIP
18 16057-P-100_H3K27ac_Cut-Tag_broad 16057-P-100_H3K27ac_Cut-Tag_broad
19 16057-P-100_H3K27ac_Cut-Tag       16057-P-100_H3K27ac_Cut-Tag
20 16057-P-200_H3K27ac_ChIP          16057-P-200_H3K27ac_ChIP
21 16057-P-200_H3K27ac_Cut-Tag_broad 16057-P-200_H3K27ac_Cut-Tag_broad
22 16057-P-200_H3K27ac_Cut-Tag       16057-P-200_H3K27ac_Cut-Tag
23 16170-C_H3K27ac_ChIP              16170-C_H3K27ac_ChIP
24 16170-P_H3K27ac_ChIP              16170-P_H3K27ac_ChIP
25 17170-P_H3K27ac_Cut-Tag_broad     17170-P_H3K27ac_Cut-Tag_broad
26 17170-P_H3K27ac_Cut-Tag           17170-P_H3K27ac_Cut-Tag
27 19019-C_H3K27ac_ChIP              19019-C_H3K27ac_ChIP
28 19019-C_H3K27ac_Cut-Tag_broad     19019-C_H3K27ac_Cut-Tag_broad
29 19019-C_H3K27ac_Cut-Tag           19019-C_H3K27ac_Cut-Tag
30 19019-P_H3K27ac_ChIP              19019-P_H3K27ac_ChIP
⋮  ⋮                                 ⋮
39 04061-P-200_H3K27ac_Cut-Tag_broad 04061-P-200_H3K27ac_Cut-Tag_broad
40 04061-P-200_H3K27ac_Cut-Tag       04061-P-200_H3K27ac_Cut-Tag
41 12097-C_H3K27ac_ChIP              12097-C_H3K27ac_ChIP
42 12097-C_H3K27ac_Cut-Tag_broad     12097-C_H3K27ac_Cut-Tag_broad
43 12097-C_H3K27ac_Cut-Tag           12097-C_H3K27ac_Cut-Tag
44 12097-P_H3K27ac_ChIP              12097-P_H3K27ac_ChIP
45 14223-C_H3K27ac_ChIP              14223-C_H3K27ac_ChIP
46 14223-C_H3K27ac_Cut-Tag_broad     14223-C_H3K27ac_Cut-Tag_broad
47 14223-C_H3K27ac_Cut-Tag           14223-C_H3K27ac_Cut-Tag
48 14223-P_H3K27ac_ChIP              14223-P_H3K27ac_ChIP
49 14223-P_H3K27ac_Cut-Tag_broad     14223-P_H3K27ac_Cut-Tag_broad
50 14223-P_H3K27ac_Cut-Tag           14223-P_H3K27ac_Cut-Tag
51 16057-P-100_H3K27ac_ChIP          16057-P-100_H3K27ac_ChIP
52 16057-P-100_H3K27ac_Cut-Tag_broad 16057-P-100_H3K27ac_Cut-Tag_broad
53 16057-P-100_H3K27ac_Cut-Tag       16057-P-100_H3K27ac_Cut-Tag
54 16057-P-200_H3K27ac_ChIP          16057-P-200_H3K27ac_ChIP
55 16057-P-200_H3K27ac_Cut-Tag_broad 16057-P-200_H3K27ac_Cut-Tag_broad
56 16057-P-200_H3K27ac_Cut-Tag       16057-P-200_H3K27ac_Cut-Tag
57 16170-C_H3K27ac_ChIP              16170-C_H3K27ac_ChIP
58 16170-P_H3K27ac_ChIP              16170-P_H3K27ac_ChIP
59 17170-P_H3K27ac_Cut-Tag_broad     17170-P_H3K27ac_Cut-Tag_broad
60 17170-P_H3K27ac_Cut-Tag           17170-P_H3K27ac_Cut-Tag
61 19019-C_H3K27ac_ChIP              19019-C_H3K27ac_ChIP
62 19019-C_H3K27ac_Cut-Tag_broad     19019-C_H3K27ac_Cut-Tag_broad
63 19019-C_H3K27ac_Cut-Tag           19019-C_H3K27ac_Cut-Tag
64 19019-P_H3K27ac_ChIP              19019-P_H3K27ac_ChIP
65 19019-P_H3K27ac_Cut-Tag_broad     19019-P_H3K27ac_Cut-Tag_broad
66 19019-P_H3K27ac_Cut-Tag           19019-P_H3K27ac_Cut-Tag
67 CD19-GSE172116-1_H3K27ac_ChIP     CD19-GSE172116-1_H3K27ac_ChIP
68 CD19-GSE172116-2_H3K27ac_ChIP     CD19-GSE172116-2_H3K27ac_ChIP

To compute the counts to perform PCA and the rest of the analysis will use Deseq

In [80]:
myCounts_DF<- as.data.frame(myCounts)
Geneid<-rownames(myCounts_DF)

GeneID<-as.data.frame(Geneid)%>% 
dplyr::rename(GeneID=1)
GeneID

GeneID <- GeneID %>%
  separate(GeneID, into = c("chr", "start", "end"), sep = "_")

GeneID

consensusToCount2<-makeGRangesFromDataFrame(GeneID)

consensusToCount2

cfChrom_DDS <- DESeqDataSetFromMatrix(myCounts, metaData, design = ~Group, rowRanges = consensusToCount2)

cfChrom_DDS <- DESeq(cfChrom_DDS)

      GeneID
1     chr1_11869_14409
2     chr1_14404_29570
3     chr1_17369_17436
4     chr1_29554_31109
5     chr1_34554_36081
6     chr1_52473_53312
7     chr1_62948_63887
8     chr1_69091_70008
9     chr1_89295_133723
10    chr1_89551_91105
11    chr1_131025_134836
12    chr1_135141_135895
13    chr1_137682_137965
14    chr1_139790_140339
15    chr1_141474_173862
16    chr1_157784_157887
17    chr1_160446_161525
18    chr1_182393_184158
19    chr1_184923_200322
20    chr1_187891_187958
21    chr1_257864_297502
22    chr1_347982_348366
23    chr1_358857_365704
24    chr1_365389_501617
25    chr1_439870_440232
26    chr1_487101_489906
27    chr1_491225_493241
28    chr1_516376_516479
29    chr1_587629_594768
30    chr1_601436_724707
⋮     ⋮
59757 chrY_25813013_25814566
59758 chrY_25860943_25861268
59759 chrY_25871931_25898653
59760 chrY_25904518_25907250
59761 chrY_25918323_25918895
59762 chrY_25923388_25929826
59763 chrY_25928979_25929142
59764 chrY_25933833_25935881
59765 chrY_25943268_25954152
59766 chrY_25975549_25988069
59767 chrY_25991241_25991572
59768 chrY_25994684_25995697
59769 chrY_26002254_26008856
59770 chrY_26011435_26012237
59771 chrY_26055779_26088493
59772 chrY_26123674_26133308
59773 chrY_26198331_26208148
59774 chrY_26244351_26244573
59775 chrY_26247384_26247521
59776 chrY_26277923_26354418
59777 chrY_26360989_26361092
59778 chrY_26400611_26401230
59779 chrY_26409815_26420535
59780 chrY_26453982_26454092
59781 chrY_26508213_26579690
59782 chrY_26549425_26549743
59783 chrY_26586642_26591601
59784 chrY_26594851_26634652
59785 chrY_26626520_26627159
59786 chrY_56855244_56855488

Warning message:
“Expected 3 pieces. Additional pieces discarded in 3621 rows [53298, 53299,
53300, 53301, 53302, 53303, 53304, 53305, 53306, 53307, 53308, 53309, 53310,
53311, 53312, 53313, 53314, 53315, 53316, 53317, ...].”

      chr  start    end
1     chr1 11869    14409
2     chr1 14404    29570
3     chr1 17369    17436
4     chr1 29554    31109
5     chr1 34554    36081
6     chr1 52473    53312
7     chr1 62948    63887
8     chr1 69091    70008
9     chr1 89295    133723
10    chr1 89551    91105
11    chr1 131025   134836
12    chr1 135141   135895
13    chr1 137682   137965
14    chr1 139790   140339
15    chr1 141474   173862
16    chr1 157784   157887
17    chr1 160446   161525
18    chr1 182393   184158
19    chr1 184923   200322
20    chr1 187891   187958
21    chr1 257864   297502
22    chr1 347982   348366
23    chr1 358857   365704
24    chr1 365389   501617
25    chr1 439870   440232
26    chr1 487101   489906
27    chr1 491225   493241
28    chr1 516376   516479
29    chr1 587629   594768
30    chr1 601436   724707
⋮     ⋮    ⋮        ⋮
59757 chrY 25813013 25814566
59758 chrY 25860943 25861268
59759 chrY 25871931 25898653
59760 chrY 25904518 25907250
59761 chrY 25918323 25918895
59762 chrY 25923388 25929826
59763 chrY 25928979 25929142
59764 chrY 25933833 25935881
59765 chrY 25943268 25954152
59766 chrY 25975549 25988069
59767 chrY 25991241 25991572
59768 chrY 25994684 25995697
59769 chrY 26002254 26008856
59770 chrY 26011435 26012237
59771 chrY 26055779 26088493
59772 chrY 26123674 26133308
59773 chrY 26198331 26208148
59774 chrY 26244351 26244573
59775 chrY 26247384 26247521
59776 chrY 26277923 26354418
59777 chrY 26360989 26361092
59778 chrY 26400611 26401230
59779 chrY 26409815 26420535
59780 chrY 26453982 26454092
59781 chrY 26508213 26579690
59782 chrY 26549425 26549743
59783 chrY 26586642 26591601
59784 chrY 26594851 26634652
59785 chrY 26626520 26627159
59786 chrY 56855244 56855488

ERROR: Error in .get_data_frame_col_as_numeric(df, granges_cols[["start"]]): some values in the "start" column cannot be turned into numeric values

  GeneID
1 chr1_11869_14409
2 chr1_14404_29570
3 chr1_17369_17436
4 chr1_29554_31109
5 chr1_34554_36081
6 chr1_52473_53312

Joining with `by = join_by(GeneID)`

In [47]:
regionsToCount

      GeneID                 chr  start    end      Strand
1     chr1_11869_14409       chr1  11869    14409   +
2     chr1_14404_29570       chr1  14404    29570   -
3     chr1_17369_17436       chr1  17369    17436   -
4     chr1_29554_31109       chr1  29554    31109   +
5     chr1_34554_36081       chr1  34554    36081   -
6     chr1_52473_53312       chr1  52473    53312   +
7     chr1_62948_63887       chr1  62948    63887   +
8     chr1_69091_70008       chr1  69091    70008   +
9     chr1_89295_133723      chr1  89295   133723   -
10    chr1_89551_91105       chr1  89551    91105   -
11    chr1_131025_134836     chr1 131025   134836   +
12    chr1_135141_135895     chr1 135141   135895   -
13    chr1_137682_137965     chr1 137682   137965   -
14    chr1_139790_140339     chr1 139790   140339   -
15    chr1_141474_173862     chr1 141474   173862   -
16    chr1_157784_157887     chr1 157784   157887   -
17    chr1_160446_161525     chr1 160446   161525   +
18    chr1_182393_184158     chr1 182393   184158   +
19    chr1_184923_200322     chr1 184923   200322   -
20    chr1_187891_187958     chr1 187891   187958   -
21    chr1_257864_297502     chr1 257864   297502   -
22    chr1_347982_348366     chr1 347982   348366   -
23    chr1_358857_365704     chr1 358857   365704   +
24    chr1_365389_501617     chr1 365389   501617   -
25    chr1_439870_440232     chr1 439870   440232   +
26    chr1_487101_489906     chr1 487101   489906   +
27    chr1_491225_493241     chr1 491225   493241   -
28    chr1_516376_516479     chr1 516376   516479   -
29    chr1_587629_594768     chr1 587629   594768   +
30    chr1_601436_724707     chr1 601436   724707   -
⋮     ⋮                      ⋮    ⋮        ⋮        ⋮
59758 chrY_25813013_25814566 chrY 25813013 25814566 +
59759 chrY_25860943_25861268 chrY 25860943 25861268 +
59760 chrY_25871931_25898653 chrY 25871931 25898653 -
59761 chrY_25904518_25907250 chrY 25904518 25907250 +
59762 chrY_25918323_25918895 chrY 25918323 25918895 -
59763 chrY_25923388_25929826 chrY 25923388 25929826 +
59764 chrY_25928979_25929142 chrY 25928979 25929142 +
59765 chrY_25933833_25935881 chrY 25933833 25935881 -
59766 chrY_25943268_25954152 chrY 25943268 25954152 +
59767 chrY_25975549_25988069 chrY 25975549 25988069 +
59768 chrY_25991241_25991572 chrY 25991241 25991572 -
59769 chrY_25994684_25995697 chrY 25994684 25995697 -
59770 chrY_26002254_26008856 chrY 26002254 26008856 +
59771 chrY_26011435_26012237 chrY 26011435 26012237 +
59772 chrY_26055779_26088493 chrY 26055779 26088493 -
59773 chrY_26123674_26133308 chrY 26123674 26133308 +
59774 chrY_26198331_26208148 chrY 26198331 26208148 -
59775 chrY_26244351_26244573 chrY 26244351 26244573 -
59776 chrY_26247384_26247521 chrY 26247384 26247521 +
59777 chrY_26277923_26354418 chrY 26277923 26354418 -
59778 chrY_26360989_26361092 chrY 26360989 26361092 +
59779 chrY_26400611_26401230 chrY 26400611 26401230 +
59780 chrY_26409815_26420535 chrY 26409815 26420535 +
59781 chrY_26453982_26454092 chrY 26453982 26454092 +
59782 chrY_26508213_26579690 chrY 26508213 26579690 +
59783 chrY_26549425_26549743 chrY 26549425 26549743 +
59784 chrY_26586642_26591601 chrY 26586642 26591601 -
59785 chrY_26594851_26634652 chrY 26594851 26634652 -
59786 chrY_26626520_26627159 chrY 26626520 26627159 -
59787 chrY_56855244_56855488 chrY 56855244 56855488 +